import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "ByteBool",
    kind: "class",
    type: "ByteBool",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    inheritsFrom: "Boolean",
    description: "Alias booleano compatível com Delphi armazenado em 1 byte.",
  },
  {
    name: "LongBool",
    kind: "class",
    type: "LongBool",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    inheritsFrom: "Boolean",
    description: "Alias booleano compatível com Delphi armazenado em 4 bytes.",
  },
  {
    name: "WordBool",
    kind: "class",
    type: "WordBool",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    inheritsFrom: "Boolean",
    description: "Alias booleano compatível com Delphi armazenado em 2 bytes.",
  },
  {
    name: "TAnsiStringDynArray",
    kind: "class",
    type: "TAnsiStringDynArray",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    description: "Array dinâmico de AnsiString retornado por operações oficiais de string.",
  },
  {
    name: "TStringDynArray",
    kind: "class",
    type: "TStringDynArray",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    description: "Array dinâmico de String retornado por operações oficiais de string.",
  },
  {
    name: "MilliSecondOf",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TDateTime",
    description: "Alias de compatibilidade para acessar os milissegundos com chamada de metodo.",
  },
];
