import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Boolean",
    kind: "class",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    inheritsFrom: "TPrimitive",
    fileUri: SYSTEM_URI,
    description: "Tipo primitivo lógico (True ou False).",
  },
  // {
  //   name: "ToString",
  //   kind: "method",
  //   type: "String",
  //   isShared: false,
  //   isPrivate: false,
  //   parameters: [],
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: SYSTEM_URI,
  //   containerName: "Boolean",
  //   description: 'Converte o valor lógico para string ("True" ou "False").',
  // },
  // {
  //   name: "Boolean",
  //   kind: "class",
  //   type: "Boolean",
  //   isShared: false,
  //   isPrivate: false,
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: SYSTEM_URI,
  //   inheritsFrom: "TObject",
  //   description: "Representa um valor lógico Verdadeiro (True) ou Falso (False).",
  // },
  // {
  //   name: "ToString",
  //   kind: "method",
  //   type: "String",
  //   isShared: false,
  //   isPrivate: false,
  //   parameters: [],
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: SYSTEM_URI,
  //   containerName: "Boolean",
  //   description: 'Retorna a representação em texto do valor booleano ("True" ou "False").',
  // },
];
