import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "StringList",
    kind: "class",
    type: "StringList",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Collections",
    inheritsFrom: "Collections.TStringList",
    description:
      "Classe nativa para manipulação de listas de strings, pares chave-valor e textos longos.",
  },
  {
    name: "Add",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Adiciona uma string na lista e retorna o índice adicionado.",
  },
  {
    name: "AddObject",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pObj",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Adiciona uma string associada a um objeto na lista.",
  },
  {
    name: "Count",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Quantidade de elementos na lista.",
  },
  {
    name: "Strings",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Retorna a string presente no índice especificado.",
  },
  {
    name: "Objects",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Retorna o objeto associado no índice especificado.",
  },
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Todo o conteúdo do StringList concatenado e separado por quebras de linha.",
  },
  {
    name: "Clear",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Esvazia a lista inteira.",
  },
  {
    name: "Delete",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Remove o elemento do índice indicado da lista.",
  },
  {
    name: "IndexOfName",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Localiza o índice do par Nome=Valor cujo nome corresponde ao parâmetro.",
  },
  {
    name: "IndexOf",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pValue",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description:
      "Retorna o índice da primeira ocorrência da string especificada na lista, ou -1 se não for encontrada.",
  },
  {
    name: "Values",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Retorna o valor associado à chave em um par Nome=Valor.",
  },
  {
    name: "NameValueSeparator",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: 'Caractere separador de chaves e valores (padrão é "=").',
  },
  {
    name: "LineBreak",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Caractere separador de quebras de linha para a propriedade Text.",
  },
  {
    name: "Insert",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Insere uma linha no índice indicado.",
  },
  {
    name: "Equals",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Compara duas strings.",
  },
  {
    name: "IndexOfObject",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pObj",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Retorna o índice da primeira ocorrência do objeto especificado na lista.",
  },
  {
    name: "AddStrings",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pList",
        type: "StringList",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Adiciona strings de outro objeto StringList à lista.",
  },
  {
    name: "Append",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Adiciona uma string à lista de strings.",
  },
  {
    name: "Assign",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pSource",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Copia o conteúdo de outro objeto compatível para esta lista.",
  },
  {
    name: "BeginUpdate",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description:
      "Chame BeginUpdate antes de modificar diretamente as sequências de caracteres na lista.",
  },
  {
    name: "EndUpdate",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Chame EndUpdate para finalizar modificações na lista de strings.",
  },
  {
    name: "Exchange",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex1",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pIndex2",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Utilize o Exchange para reorganizar as sequências de caracteres na lista.",
  },
  {
    name: "InsertObject",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pText",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pObj",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Insere uma string na lista na posição especificada e a associa a um objeto.",
  },
  {
    name: "SaveToFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pFileName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Salva as strings em um arquivo de texto.",
  },
  {
    name: "LoadFromFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pFileName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Preenche uma lista de strings com os dados de um arquivo físico.",
  },
  {
    name: "Move",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pCurIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pNewIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Altera a posição de uma sequência na lista.",
  },
  {
    name: "Capacity",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Capacidade máxima de Strings que poderão ser adicionadas à lista.",
  },
  {
    name: "CommaText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Lista formatada/obtida por meio de uma string separada por vírgulas.",
  },
  {
    name: "Names",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pIndex",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Retorna a parte de nome de um par chave-valor no índice indicado.",
  },
  {
    name: "OwnsObjects",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Especifica se a lista possui a propriedade dos objetos armazenados.",
  },
  {
    name: "Sorted",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "StringList",
    description: "Ordena a lista de strings por ordem ascendente.",
  },
];
