import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TObjectList",
    kind: "class",
    type: "TObjectList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    inheritsFrom: "TObject",
    description: "Classe que armazena uma lista de objetos.",
  },
  {
    name: "Add",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pItem", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Adiciona um objeto à lista.",
  },
  {
    name: "Count",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Retorna a quantidade de objetos contidos na lista.",
  },
  {
    name: "Clear",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Remove todos os objetos da lista.",
  },
  {
    name: "Insert",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }, {
      name: "pItem",
      type: "TObject",
      isByRef: false,
      isOptional: false,
    }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Insere um objeto na posição especificada.",
  },
  {
    name: "Delete",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Remove o objeto na posição especificada.",
  },
  {
    name: "Item",
    kind: "indexed-property",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObjectList",
    description: "Acessa o objeto na posição especificada.",
  },
];
