import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TStrings",
    kind: "class",
    type: "TStrings",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Collections",
    inheritsFrom: "System.Classes.TPersistent",
    description:
      "Classe base para manipulação de coleções de strings associadas a objetos, disponível no namespace Collections.",
  },
  {
    name: "Add",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pText", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Adiciona uma string na lista e retorna o índice correspondente.",
  },
  {
    name: "AddObject",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pText", type: "String", isByRef: false, isOptional: false },
      { name: "pObj", type: "TObject", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Adiciona uma string associada a um objeto na lista.",
  },
  {
    name: "AddPair",
    kind: "method",
    type: "TStrings",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pName", type: "String", isByRef: false, isOptional: false },
      { name: "pValue", type: "String", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Adiciona um par Nome=Valor na lista.",
  },
  {
    name: "AddStrings",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pList", type: "TStrings", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Adiciona os itens de outra lista nesta lista.",
  },
  {
    name: "Append",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pText", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Adiciona uma string ao final da lista.",
  },
  {
    name: "Assign",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pSource", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Copia o conteúdo de outra lista de strings.",
  },
  {
    name: "BeginUpdate",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Bloqueia atualizações visuais da lista de strings.",
  },
  {
    name: "EndUpdate",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Libera atualizações visuais da lista de strings.",
  },
  {
    name: "Clear",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Limpa toda a lista e deleta as strings e objetos.",
  },
  {
    name: "Delete",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Remove o item do índice indicado.",
  },
  {
    name: "Equals",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pStrings", type: "TStrings", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Compara esta lista de strings com outra.",
  },
  {
    name: "Exchange",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pIndex1", type: "Integer", isByRef: false, isOptional: false },
      { name: "pIndex2", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Inverte a posição de duas strings na lista.",
  },
  {
    name: "IndexOf",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pText", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o índice correspondente à string fornecida, ou -1.",
  },
  {
    name: "IndexOfName",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o índice do par Nome=Valor contendo o nome fornecido.",
  },
  {
    name: "IndexOfObject",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pObj", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o índice da string associada ao objeto informado.",
  },
  {
    name: "Insert",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pIndex", type: "Integer", isByRef: false, isOptional: false },
      { name: "pText", type: "String", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Insere uma string na lista na posição especificada.",
  },
  {
    name: "InsertObject",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pIndex", type: "Integer", isByRef: false, isOptional: false },
      { name: "pText", type: "String", isByRef: false, isOptional: false },
      { name: "pObj", type: "TObject", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Insere uma string associada a um objeto na posição especificada.",
  },
  {
    name: "LoadFromFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pFileName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Carrega a lista de strings com o conteúdo de um arquivo de texto.",
  },
  {
    name: "LoadFromStream",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pStream", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Carrega a lista de strings a partir de um stream de dados.",
  },
  {
    name: "Move",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pCurIndex", type: "Integer", isByRef: false, isOptional: false },
      { name: "pNewIndex", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Altera o índice da string selecionada.",
  },
  {
    name: "SaveToFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pFileName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Salva a lista de strings em um arquivo físico no disco.",
  },
  {
    name: "SaveToStream",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pStream", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Salva o conteúdo em formato de texto para um stream.",
  },
  {
    name: "Strings",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna ou altera a string em uma posição indicada da lista.",
  },
  {
    name: "Item",
    kind: "indexed-property",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Default indexed property para acesso direto com colchetes: lista[i].",
  },
  {
    name: "Objects",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o objeto associado à string na posição indicada.",
  },
  {
    name: "Names",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o nome correspondente do par Nome=Valor no índice indicado.",
  },
  {
    name: "Values",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description:
      "Retorna ou define o valor correspondente de um par Nome=Valor através do nome informado.",
  },
  {
    name: "ValueFromIndex",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pIndex", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna o valor correspondente do par Nome=Valor no índice indicado.",
  },
  {
    name: "Capacity",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Indica a capacidade máxima atual de strings que a lista pode comportar.",
  },
  {
    name: "CommaText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Conteúdo inteiro da lista representado em uma linha delimitado por vírgulas.",
  },
  {
    name: "Count",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna a quantidade total de elementos presentes na lista.",
  },
  {
    name: "Delimiter",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Define o caractere delimitador usado para gerar e carregar dados delimitados.",
  },
  {
    name: "DelimitedText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Retorna ou analisa toda a lista em uma única string delimitada.",
  },
  {
    name: "LineBreak",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Define os caracteres usados para quebra de linha.",
  },
  {
    name: "NameValueSeparator",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Informa o caractere separador de par Nome=Valor (padrão '=').",
  },
  {
    name: "QuoteChar",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Informa o caractere usado para aspas.",
  },
  {
    name: "StrictDelimiter",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Especifica se o Delimiter deve ser interpretado estritamente.",
  },
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description:
      "Retorna ou define todos os elementos em uma única string concatenada com quebra de linhas.",
  },
  {
    name: "TrailingLineBreak",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStrings",
    description: "Informa se deve incluir uma quebra de linha na última linha da propriedade Text.",
  },
];
