import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TStringList",
    kind: "class",
    type: "TStringList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Collections",
    inheritsFrom: "Collections.TStrings",
    description:
      "Classe de lista de strings com suporte a ordenação, busca e controle de duplicatas.",
  },
  {
    name: "Find",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "pText", type: "String", isByRef: false, isOptional: false },
      { name: "pIndex", type: "Integer", isByRef: true, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description:
      "Busca uma string na lista ordenada e retorna true se encontrada, preenchendo o índice em pIndex.",
  },
  {
    name: "Sort",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description: "Ordena os itens da lista em ordem ascendente.",
  },
  {
    name: "CustomSort",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pCompare", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description:
      "Ordena os itens da lista usando um método customizado de comparação de objetos/strings.",
  },
  {
    name: "CaseSensitive",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description: "Especifica se as buscas e comparações diferenciam maiúsculas de minúsculas.",
  },
  {
    name: "Duplicates",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description:
      "Controla a política de inserção de duplicatas (ex: dupIgnore, dupAccept, dupError).",
  },
  {
    name: "Sorted",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description: "Especifica se a lista deve manter os elementos automaticamente ordenados.",
  },
  {
    name: "OwnsObjects",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TStringList",
    description:
      "Especifica se a lista deve liberar a memória dos objetos contidos ao limpá-la ou remover itens.",
  },
];
