import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TObject",
    kind: "class",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes",
    description: "Classe base de todos os objetos nativos Delphi no namespace System.Classes.",
  },
  {
    name: "Create",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Construtor padrão da classe TObject.",
  },
  {
    name: "Destroy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Destrutor padrão da classe TObject.",
  },
  {
    name: "Free",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Libera o objeto e destrói sua instância se ela não for nula.",
  },
  {
    name: "DisposeOf",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Força a destruição do objeto.",
  },
  {
    name: "ClassName",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Retorna o nome da classe do objeto.",
  },
  {
    name: "ClassNameIs",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Verifica se o nome da classe corresponde à string informada.",
  },
  {
    name: "ClassParent",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Retorna a classe pai do objeto.",
  },
  {
    name: "InheritsFrom",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pClass",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Determina se a classe herda de uma determinada classe.",
  },
  {
    name: "ToString",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Retorna a representação em texto do objeto.",
  },
  {
    name: "GetHashCode",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Retorna o código hash identificador único do objeto.",
  },
  {
    name: "InstanceSize",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Retorna o tamanho em bytes de cada instância da classe.",
  },
  {
    name: "AfterConstruction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Método executado automaticamente após a construção do objeto.",
  },
  {
    name: "BeforeDestruction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "System.Classes.TObject",
    description: "Método executado automaticamente antes da destruição do objeto.",
  },
];
