import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "FlatButton",
    kind: "class",
    type: "FlatButton",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TGraphicControl",
    description:
      "Botão visual chato (flat) baseado em TSpeedButton — renderizado pelo Canvas do pai, sem janela própria. Ideal para barras de ferramentas.",
  },

  // ───────── Properties ─────────
  {
    name: "Caption",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Texto exibido no botão.",
  },
  {
    name: "Glyph",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description:
      "Imagem (bitmap) exibida no botão. Pode conter até 4 estados (normal, disabled, clicked, down).",
  },
  {
    name: "NumGlyphs",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Quantidade de imagens contidas em Glyph (1 a 4).",
  },
  {
    name: "Flat",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Se o botão é renderizado em estilo flat (sem borda 3D destacada).",
  },
  {
    name: "GroupIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description:
      "Identifica o grupo de botões mutualmente exclusivos (radio behavior). 0 = sem grupo.",
  },
  {
    name: "Down",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Estado pressionado do botão (quando GroupIndex > 0).",
  },
  {
    name: "AllowAllUp",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Se todos os botões do grupo podem estar simultaneamente desativados.",
  },
  {
    name: "Layout",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description:
      "Posição do glyph em relação ao caption (blGlyphLeft, blGlyphRight, blGlyphTop, blGlyphBottom).",
  },

  // ───────── Events ─────────
  {
    name: "OnClick",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "FlatButton",
    description: "Ocorre quando o botão é clicado.",
  },
];
