import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "HComboBox",
    kind: "class",
    type: "HComboBox",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TcxCustomTextEdit",
    description: "Caixa de seleção dropdown (combobox) padrão Data7. Wrapper sobre TcxComboBox.",
  },

  // ───────── Properties ─────────
  // BeepOnEnter, ItemIndex, ItemObject e Properties são herdados de TcxCustomTextEdit/TcxCustomEdit.
  {
    name: "CanDropDown",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Identifica se a lista dropdown pode ser aberta no estado atual do editor.",
  },
  {
    name: "PopupWindow",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Acesso à janela popup que exibe a lista de itens do combobox.",
  },

  // ───────── Properties (Data7-specific HComboBox: lista chave/valor) ─────────
  {
    name: "Items",
    kind: "property",
    type: "TStringList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Lista de itens visíveis do combobox (TStrings). Cada string é uma opção exibida.",
  },
  {
    name: "ListaOpcoes",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description:
      "Lista de opções no formato 'codigo:descricao;codigo:descricao;...' — atribuição em massa via string.",
  },
  {
    name: "ValueList",
    kind: "property",
    type: "TStringList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Lista paralela de valores associados a cada item visível (chaves).",
  },
  {
    name: "ValueSelect",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Valor (chave) correspondente ao item atualmente selecionado.",
  },
  {
    name: "SelectedItem",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "HComboBox",
    description: "Texto do item atualmente selecionado na lista.",
  },
];
