import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "MemoTextBox",
    kind: "class",
    type: "MemoTextBox",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TcxCustomTextEdit",
    description: "Caixa de texto multilinha do Data7 (TMemoEditor). Wrapper sobre TcxMemo.",
  },

  // ───────── Properties ─────────
  {
    name: "Lines",
    kind: "property",
    type: "TStringList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "MemoTextBox",
    description: "Lista de linhas do memo (TStrings). Cada item corresponde a uma linha textual.",
  },
  {
    name: "WantReturns",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "MemoTextBox",
    description: "Se ENTER insere quebra de linha no memo (True) ou é roteado para o form (False).",
  },
  {
    name: "WantTabs",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "MemoTextBox",
    description: "Se TAB insere caractere de tabulação no memo (True) ou avança o foco (False).",
  },
  {
    name: "WordWrap",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "MemoTextBox",
    description: "Se linhas longas quebram automaticamente no fim da área visível.",
  },
  {
    name: "ScrollBars",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "MemoTextBox",
    description: "Quais barras de rolagem exibir (ssNone, ssHorizontal, ssVertical, ssBoth).",
  },
];
