import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "ProgressBar",
    kind: "class",
    type: "ProgressBar",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TWinControl",
    description:
      "Barra de progresso nativa do Windows. Exibe o avanço de uma operação entre Min e Max. Wrapper sobre TProgressBar (Vcl.ComCtrls).",
  },

  // ───────── Properties ─────────
  {
    name: "BackgroundColor",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Cor de fundo da barra de progresso.",
  },
  {
    name: "BarColor",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Cor da parte preenchida (highlight) da barra de progresso.",
  },
  {
    name: "MarqueeInterval",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Tempo em milissegundos entre updates da animação marquee.",
  },
  {
    name: "Max",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Limite superior do intervalo de posições possíveis.",
  },
  {
    name: "Min",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Limite inferior do intervalo de posições possíveis.",
  },
  {
    name: "Orientation",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Se a barra é horizontal (pbHorizontal) ou vertical (pbVertical).",
  },
  {
    name: "Position",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Posição atual da barra de progresso (entre Min e Max).",
  },
  {
    name: "Smooth",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Se a barra é renderizada de forma contínua (True) ou segmentada/blocos (False).",
  },
  {
    name: "SmoothReverse",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Se permite mostrar o decréscimo de progresso de forma suave.",
  },
  {
    name: "State",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Estado atual: pbsNormal (verde), pbsError (vermelho) ou pbsPaused (amarelo).",
  },
  {
    name: "Step",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Quantidade pela qual Position é incrementada quando StepIt é chamado.",
  },
  {
    name: "Style",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description:
      "Como o progresso é ilustrado (pbstNormal — barra padrão, pbstMarquee — animação contínua).",
  },

  // ───────── Methods ─────────
  {
    name: "StepBy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Delta", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Avança Position em uma quantidade específica (delta).",
  },
  {
    name: "StepIt",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "ProgressBar",
    description: "Avança Position pela quantidade especificada em Step.",
  },
];
