import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TButtonControl",
    kind: "class",
    type: "TButtonControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TWinControl",
    description:
      "Classe base dos botões nativos do Windows (consolidando TButtonControl + TCustomButton + TButton + TBotao do Data7). Introduz comportamento de clique, foco com TAB, atalhos via acelerador (&), botões default/cancel, ícones e estilos.",
  },

  // ───────── Properties (TCustomButton) ─────────
  {
    name: "Cancel",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Se o OnClick do botão é executado quando a tecla Escape é pressionada.",
  },
  {
    name: "CommandLinkHint",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Texto exibido como hint abaixo do caption (Command Link).",
  },
  {
    name: "Default",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Se o OnClick do botão é executado quando a tecla Enter é pressionada.",
  },
  {
    name: "DisabledImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado desabilitado.",
  },
  {
    name: "DropDownMenu",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Menu drop-down do split button.",
  },
  {
    name: "ElevationRequired",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Coloca o ícone de escudo no botão, indicando que é necessária elevação UAC.",
  },
  {
    name: "HotImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado hot (hover).",
  },
  {
    name: "ImageAlignment",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Alinhamento da imagem no botão.",
  },
  {
    name: "ImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado normal.",
  },
  {
    name: "ImageMargins",
    kind: "property",
    type: "TMargins",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Margens da imagem no botão.",
  },
  {
    name: "Images",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Lista de imagens (ImageList) usada pelo botão.",
  },
  {
    name: "ModalResult",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description:
      "Determina como o botão fecha seu formulário pai (mrOk, mrCancel, mrYes, mrNo, etc.).",
  },
  {
    name: "PressedImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado pressionado.",
  },
  {
    name: "SelectedImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado selecionado.",
  },
  {
    name: "Style",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Estilo do botão (bsPushButton, bsCommandLink, bsSplitButton).",
  },
  {
    name: "StylusHotImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Índice da imagem usada no estado hot via stylus (caneta touch).",
  },
  {
    name: "Caption",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: 'Texto exibido no botão. Use & para acelerador (ex: "&Ok").',
  },

  // ───────── Methods (TCustomButton) ─────────
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Alias textual usado pelo Data7 para o caption do botao.",
  },
  {
    name: "Click",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Simula um clique do mouse, como se o usuário tivesse clicado no botão.",
  },

  // ───────── Events ─────────
  {
    name: "OnClick",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description: "Ocorre quando o usuário clica no botão.",
  },
  {
    name: "OnDropDownClick",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TButtonControl",
    description:
      "Ocorre quando a parte da seta para baixo de um split button (estilo Vista+) é clicada.",
  },
];
