import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TComponent",
    kind: "class",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TPersistent",
    description:
      "Ancestral comum de todos os componentes Delphi (visuais e não visuais). Introduz integração com a IDE, sistema de ownership, streaming/persistência e suporte a COM.",
  },

  // ───────── Properties ─────────
  {
    name: "ComponentCount",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Quantidade de componentes que este componente possui (é dono).",
  },
  {
    name: "ComponentIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Posição do componente no array Components do seu Owner.",
  },
  {
    name: "Components",
    kind: "property",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Lista todos os componentes de propriedade (owned) deste componente.",
  },
  {
    name: "ComponentState",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Estado atual do componente — indica quando o componente deve evitar certas ações (carregando, destruindo, etc.).",
  },
  {
    name: "ComponentStyle",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Governa o comportamento do componente (csInheritable, csCheckPropAvail, csSubComponent, csTransient, etc.).",
  },
  {
    name: "DesignInfo",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Informações usadas pelo Form Designer (posição na palette/grid).",
  },
  {
    name: "Name",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Nome do componente como ele é referenciado em código.",
  },
  {
    name: "Observers",
    kind: "property",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Indica o objeto TObservers anexado ao componente (padrão Observer).",
  },
  {
    name: "Owner",
    kind: "property",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Componente responsável por liberar este componente da memória (streaming + ownership).",
  },
  {
    name: "Tag",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Valor inteiro de uso geral, armazenado junto ao componente para conveniência do desenvolvedor.",
  },
  {
    name: "VCLComObject",
    kind: "property",
    type: "Pointer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Ponteiro para a instância COM/VCL associada ao componente (usado por servidores Automation).",
  },

  // ───────── Methods ─────────
  {
    name: "BeforeDestruction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Executa ações necessárias antes do primeiro destrutor ser chamado.",
  },
  {
    name: "BeginInvoke",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Chamada assíncrona do método especificado por AProc ou AFunc.",
  },
  {
    name: "Create",
    kind: "method",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AOwner", type: "TComponent", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Aloca memória e constrói uma instância de componente inicializada com segurança.",
  },
  {
    name: "Destroy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Destrói o componente e seus componentes de propriedade (owned).",
  },
  {
    name: "DestroyComponents",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Destrói todos os componentes de propriedade (owned).",
  },
  {
    name: "Destroying",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Indica que o componente e seus owned estão prestes a serem destruídos.",
  },
  {
    name: "EndFunctionInvoke",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Bloqueia o chamador até que o ASyncResult especificado seja concluído.",
  },
  {
    name: "EndInvoke",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Bloqueia o chamador até que o ASyncResult especificado seja concluído.",
  },
  {
    name: "ExecuteAction",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Action", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Executa uma Action associada ao componente.",
  },
  {
    name: "FindComponent",
    kind: "method",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Indica se um componente específico é de propriedade deste componente.",
  },
  {
    name: "FreeNotification",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AComponent", type: "TComponent", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Garante que AComponent será notificado quando este componente for destruído.",
  },
  {
    name: "FreeOnRelease",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Libera a referência de interface para componentes criados a partir de classes COM.",
  },
  {
    name: "GetEnumerator",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Retorna um enumerador sobre os Components do componente.",
  },
  {
    name: "GetNamePath",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Retorna a string usada pelo Object Inspector para representar o componente.",
  },
  {
    name: "GetParentComponent",
    kind: "method",
    type: "TComponent",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Retorna o componente que contém este componente (parent).",
  },
  {
    name: "HasParent",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Verifica se o componente possui um parent.",
  },
  {
    name: "InsertComponent",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AComponent", type: "TComponent", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Estabelece este componente como o owner do componente especificado.",
  },
  {
    name: "IsImplementorOf",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "I", type: "Variant", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Indica se o componente implementa uma interface especificada.",
  },
  {
    name: "ReferenceInterface",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description:
      "Estabelece ou remove links internos que fazem este componente ser notificado quando o implementador de uma interface for destruído.",
  },
  {
    name: "RemoveComponent",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AComponent", type: "TComponent", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Remove o componente especificado da lista Components.",
  },
  {
    name: "RemoveFreeNotification",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AComponent", type: "TComponent", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Desativa a notificação de destruição registrada por FreeNotification.",
  },
  {
    name: "SafeCallException",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Trata exceções em métodos declarados com a convenção de chamada safecall.",
  },
  {
    name: "SetSubComponent",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "IsSubComponent", type: "Boolean", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Identifica se o componente é um subcomponente.",
  },
  {
    name: "UpdateAction",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Action", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TComponent",
    description: "Atualiza o estado de uma Action.",
  },
];
