import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TcxCustomTextEdit",
    kind: "class",
    type: "TcxCustomTextEdit",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TcxCustomEdit",
    description:
      "Especialização de TcxCustomEdit para entradas textuais. Adiciona Text, seleção, hint inline (TextHint), histórico de Undo e operações de caret/clipboard; é a base de todos os editores textuais DevExpress (TextBox, PasswordTextBox, MaskTextBox, MemoTextBox, etc.).",
  },

  // ───────── Properties ─────────
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Texto exibido/editado no controle.",
  },
  {
    name: "TextHint",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Mensagem de dica (placeholder) exibida dentro do editor quando vazio.",
  },
  {
    name: "EditingText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Acessa e modifica o conteúdo textual em edição (independente de display masks).",
  },
  {
    name: "ParentColor",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Se o editor de texto usa a cor do parent para preencher o background.",
  },
  {
    name: "SelStart",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Posição inicial (índice) da seleção dentro do texto.",
  },
  {
    name: "SelLength",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Comprimento da seleção em caracteres.",
  },
  {
    name: "CursorPos",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Posição do cursor (caret) dentro do editor.",
  },

  {
    name: "SelText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Texto atualmente selecionado dentro do editor.",
  },
  {
    name: "EditText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description:
      "Acessa o texto raw que está sendo editado (independente de máscaras e formatação de display). Trazido de TcxCustomMaskEdit pela simplificação da árvore.",
  },
  {
    name: "BeepOnEnter",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Se o editor emite um beep quando o usuário pressiona Enter no campo.",
  },
  {
    name: "ItemIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description:
      "Índice (zero-based) do item correspondente na lista de auto-complete/lookup, quando aplicável.",
  },
  {
    name: "ItemObject",
    kind: "property",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Objeto auxiliar associado ao item atualmente selecionado.",
  },

  // ───────── Methods ─────────
  {
    name: "SetSelection",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "AStart", type: "Integer", isByRef: false, isOptional: false },
      { name: "ALength", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Seleciona um intervalo de texto no editor (start + length em caracteres).",
  },
  {
    name: "ClearSelection",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Remove a seleção atual sem alterar o texto.",
  },
  {
    name: "Undo",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Desfaz a última alteração de conteúdo enquanto o editor permanece focado.",
  },
  {
    name: "FindSelection",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "ASearchText", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Procura e seleciona um texto dentro do editor.",
  },

  // ───────── Comportamento textual ─────────
  // ReadOnly e OnChange são herdados de TcxCustomEdit (válidos para todos os editores, não só textuais).
  {
    name: "MaxLength",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomTextEdit",
    description: "Número máximo de caracteres permitidos no editor (0 = sem limite).",
  },
];
