import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TForm",
    kind: "class",
    type: "TForm",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TScrollingWinControl",
    description:
      "Classe base de janelas (formulários) da VCL Delphi. Adiciona suporte a posição inicial, borda, ícone, modalidade, eventos de ciclo de vida (OnCreate, OnShow, OnClose) e exibição como diálogo (ShowModal).",
  },

  // ───────── Properties (TCustomForm) ─────────
  {
    name: "Active",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Indica se o formulário tem foco.",
  },
  {
    name: "ActiveControl",
    kind: "property",
    type: "TWinControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Controle que possui o foco no formulário.",
  },
  {
    name: "ActiveOleControl",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Controle OLE no formulário que reage a mudanças de foco.",
  },
  {
    name: "BorderStyle",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Aparência e comportamento da borda do formulário (bsSizeable, bsSingle, bsDialog, bsNone, bsSizeToolWin, bsToolWindow).",
  },
  {
    name: "Canvas",
    kind: "property",
    type: "TCanvas",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Acesso à área de desenho do formulário.",
  },
  {
    name: "Designer",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Interface do designer para o formulário.",
  },
  {
    name: "DropTarget",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Se o formulário é alvo de uma operação drag-and-drop.",
  },
  {
    name: "FormState",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Informações de estado transicional do formulário.",
  },
  {
    name: "GlassFrame",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Acesso ao Glass Frame no Windows Vista, 7 ou posterior (efeito Aero).",
  },
  {
    name: "HelpFile",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Nome do arquivo de Help usado para exibir ajuda do formulário.",
  },
  {
    name: "KeyPreview",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Se o formulário recebe eventos de teclado antes do controle ativo.",
  },
  {
    name: "Menu",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Menu principal do formulário.",
  },
  {
    name: "ModalResult",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Representa o valor de retorno de um formulário exibido como diálogo modal (mrOk, mrCancel, etc.).",
  },
  {
    name: "Monitor",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Acesso ao monitor (display) onde o formulário aparece.",
  },
  {
    name: "OleFormObject",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Interface IOleForm para um objeto OLE in-place contido no formulário.",
  },
  {
    name: "PopupMode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Comportamento do formulário em relação ao estilo WS_POPUP do Windows.",
  },
  {
    name: "PopupParent",
    kind: "property",
    type: "TForm",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Define uma ordem para formulários empilhados que o usuário não pode alterar.",
  },
  {
    name: "ScreenSnap",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Se o formulário se encaixa nas bordas da tela.",
  },
  {
    name: "SnapBuffer",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Distância para o screen snap.",
  },
  {
    name: "WindowState",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Como o formulário aparece na tela (wsNormal, wsMinimized, wsMaximized).",
  },

  // ───────── Methods (TCustomForm) ─────────
  {
    name: "Close",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Fecha o formulário.",
  },
  {
    name: "CloseQuery",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Dispatcher do evento de tentativa de fechamento (consulta OnCloseQuery).",
  },
  {
    name: "DefocusControl",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Control", type: "TWinControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Remove o foco de um controle do formulário.",
  },
  {
    name: "FocusControl",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Control", type: "TWinControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Coloca o foco em um controle do formulário.",
  },
  {
    name: "GetFormImage",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Retorna um bitmap (snapshot) do formulário.",
  },
  {
    name: "IsShortCut",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Processa teclas de atalho quando o formulário tem foco.",
  },
  {
    name: "MakeFullyVisible",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Garante que o formulário esteja totalmente visível em um monitor específico.",
  },
  {
    name: "Print",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Imprime o formulário.",
  },
  {
    name: "Release",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Destrói o formulário e libera memória.",
  },
  {
    name: "SendCancelMode",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Cancela modos no formulário.",
  },
  {
    name: "SetFocusedControl",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Control", type: "TWinControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Coloca o foco em um controle do formulário.",
  },
  {
    name: "Show",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Exibe o formulário.",
  },
  {
    name: "ShowModal",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Exibe o formulário como diálogo modal e retorna o ModalResult.",
  },
  {
    name: "WantChildKey",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Indica se o formulário processa input de teclado para um controle do qual é dono.",
  },

  // ───────── Events (TCustomForm) ─────────
  {
    name: "OnActivate",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre quando o formulário se torna o formulário ativo.",
  },
  {
    name: "OnDeactivate",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre quando o formulário deixa de ser o formulário ativo.",
  },
  {
    name: "OnCreate",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Ocorre quando o formulário é criado, após todos os controles filhos terem sido carregados.",
  },
  {
    name: "OnDestroy",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre imediatamente antes da destruição do formulário.",
  },
  {
    name: "OnShow",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Ocorre quando o formulário se torna visível (após Show/ShowModal ou Visible := True).",
  },
  {
    name: "OnHide",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre quando o formulário é ocultado (após Hide ou Visible := False).",
  },
  {
    name: "OnResize",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre quando o tamanho do formulário muda.",
  },
  {
    name: "OnPaint",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ocorre quando o formulário precisa ser redesenhado.",
  },
  {
    name: "OnClose",
    kind: "property",
    type: "TCloseEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Ocorre quando o formulário está sendo fechado — permite escolher a ação (caHide, caFree, caMinimize, caNone).",
  },
  {
    name: "OnCloseQuery",
    kind: "property",
    type: "TCloseQueryEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Ocorre antes de fechar o formulário — permite cancelar o fechamento setando CanClose = False.",
  },
  {
    name: "OnAfterMonitorDpiChanged",
    kind: "property",
    type: "TMonitorDpiChangedEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Ocorre após o monitor que contém o formulário ter o DPI alterado (formulário reescalado).",
  },

  // ───────── Methods MDI (TForm próprio) ─────────
  {
    name: "ArrangeIcons",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Organiza os ícones de formulários filhos MDI minimizados.",
  },
  {
    name: "Cascade",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Organiza formulários filhos MDI em cascata (sobrepostos).",
  },
  {
    name: "Next",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ativa o próximo formulário filho na sequência.",
  },
  {
    name: "Previous",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Ativa o formulário filho MDI anterior na sequência.",
  },
  {
    name: "Tile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Organiza formulários filhos MDI lado a lado.",
  },

  // ───────── Properties (TCustomForm — adicionadas para cobertura da planilha) ─────────
  {
    name: "AlphaBlend",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Habilita a transparência (alpha blending) do formulário.",
  },
  {
    name: "AlphaBlendValue",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Valor da transparência (0=invisível, 255=opaco).",
  },
  {
    name: "AutoScroll",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Indica se as barras de rolagem aparecem automaticamente quando necessário.",
  },
  {
    name: "AutoSize",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Faz o formulário se ajustar automaticamente para conter seus controles.",
  },
  {
    name: "BorderIcons",
    kind: "property",
    type: "TBorderIcons",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Conjunto de ícones exibidos na barra de título (biSystemMenu, biMinimize, biMaximize, biHelp).",
  },
  {
    name: "BorderWidth",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Largura adicional desenhada entre a borda e a área cliente do formulário.",
  },
  {
    name: "TransparentColor",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Habilita o uso de uma cor como transparente (chave) no formulário.",
  },
  {
    name: "TransparentColorValue",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Cor usada como chave de transparência.",
  },
  {
    name: "Ctl3D",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Habilita o estilo 3D nos controles (legado pré-XP).",
  },
  {
    name: "DefaultMonitor",
    kind: "property",
    type: "TDefaultMonitor",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Define em qual monitor o formulário aparece por padrão.",
  },
  {
    name: "DoubleBufferedMode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Modo de double-buffering (auto/sempre/nunca).",
  },
  {
    name: "DragKind",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Define se o drag é de drag-and-drop ou de docking (dkDrag/dkDock).",
  },
  {
    name: "DragMode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Modo de inicialização do drag (dmManual/dmAutomatic).",
  },
  {
    name: "ParentFont",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Faz o formulário herdar a fonte do parent.",
  },
  {
    name: "Font",
    kind: "property",
    type: "TFont",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Fonte padrão usada para textos no formulário.",
  },
  {
    name: "FormStyle",
    kind: "property",
    type: "TFormStyle",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Estilo do formulário (fsNormal/fsMDIChild/fsMDIForm/fsStayOnTop).",
  },
  {
    name: "VisualManager",
    kind: "property",
    type: "IFormVisualManager",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Interface do gerenciador visual (estilos/skins) do formulário.",
  },
  {
    name: "ParentBiDiMode",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Indica se BiDiMode é herdado do parent.",
  },
  {
    name: "Position",
    kind: "property",
    type: "TPosition",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Posição inicial do formulário (poScreenCenter, poDefault, ...).",
  },
  {
    name: "PrintScale",
    kind: "property",
    type: "TPrintScale",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Define o fator de escala ao imprimir o formulário.",
  },
  {
    name: "RoundedCorners",
    kind: "property",
    type: "TRoundedCornerType",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Estilo dos cantos arredondados no Windows 11.",
  },
  {
    name: "Scaled",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Indica se o formulário ajusta tamanhos conforme o DPI da tela.",
  },
  {
    name: "TipMode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Modo de exibição das dicas (tooltips) no formulário.",
  },
  {
    name: "StyleName",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Nome do estilo VCL aplicado ao formulário.",
  },
  {
    name: "ShowInTaskBar",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Indica se o formulário aparece na barra de tarefas do Windows.",
  },

  // ───────── Events (TCustomForm — adicionados para cobertura da planilha) ─────────
  {
    name: "OnBeforeMonitorDpiChanged",
    kind: "property",
    type: "TMonitorDpiChangedEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description:
      "Disparado antes do monitor que contém o formulário ter o DPI alterado (permite preparação).",
  },
  {
    name: "OnMouseWheel",
    kind: "property",
    type: "TMouseWheelEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Disparado quando a roda do mouse é girada sobre o formulário.",
  },
  {
    name: "OnMouseWheelDown",
    kind: "property",
    type: "TMouseWheelUpDownEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Disparado quando a roda do mouse é girada para baixo.",
  },
  {
    name: "OnMouseWheelUp",
    kind: "property",
    type: "TMouseWheelUpDownEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TForm",
    description: "Disparado quando a roda do mouse é girada para cima.",
  },
];
