import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TModalResult",
    kind: "class",
    type: "TModalResult",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description:
      "Representa o valor de retorno de um diálogo modal. Use estes mrXxx em ButtonOk/ButtonCancel.ModalResult ou retorne diretamente em Form.ShowModal.",
  },

  // ───────── Constantes ─────────
  {
    name: "mrNone",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Sem resultado (0) — diálogo permanece aberto.",
  },
  {
    name: "mrOk",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Ok (1) — confirmação do usuário.",
  },
  {
    name: "mrCancel",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Cancel (2) — cancelamento pelo usuário.",
  },
  {
    name: "mrAbort",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Abort (3) — operação abortada.",
  },
  {
    name: "mrRetry",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Retry (4) — tentar novamente.",
  },
  {
    name: "mrIgnore",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Ignore (5) — ignorar e continuar.",
  },
  {
    name: "mrYes",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Yes (6) — sim.",
  },
  {
    name: "mrNo",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado No (7) — não.",
  },
  {
    name: "mrAll",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado All (8) — aplicar a tudo.",
  },
  {
    name: "mrNoToAll",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado NoToAll (9) — não para todos os itens.",
  },
  {
    name: "mrYesToAll",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado YesToAll (10) — sim para todos os itens.",
  },
  {
    name: "mrClose",
    kind: "variable",
    type: "TModalResult",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Resultado Close (11) — fechar.",
  },
];
