import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TWinControl",
    kind: "class",
    type: "TWinControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TControl",
    description:
      "Classe base para todos os controles visuais que possuem janela própria do Windows (handle HWND). Pode conter outros controles, receber foco de teclado e interagir com o sistema de mensagens nativo.",
  },

  // ───────── Properties ─────────
  {
    name: "AlignDisabled",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Indica que o realinhamento dos controles filhos está desabilitado.",
  },
  {
    name: "Brush",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Determina a cor e o padrão usados para pintar o fundo do controle.",
  },
  {
    name: "ControlCount",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Retorna a quantidade de controles filhos.",
  },
  {
    name: "Controls",
    kind: "property",
    type: "TControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Lista todos os controles filhos.",
  },
  {
    name: "DockClientCount",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Quantidade de controles encaixados neste controle.",
  },
  {
    name: "DockClients",
    kind: "property",
    type: "TControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Lista os controles encaixados neste controle.",
  },
  {
    name: "DockManager",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Interface do gerenciador de docking do controle.",
  },
  {
    name: "DockSite",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Se o controle pode ser alvo de operações drag-and-dock.",
  },
  {
    name: "DoubleBuffered",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description:
      "Determina se a imagem do controle é renderizada direto na janela ou pintada em um bitmap em memória primeiro.",
  },
  {
    name: "Handle",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Acesso ao handle Windows (HWND) subjacente do controle.",
  },
  {
    name: "MouseInClient",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Indica se o ponteiro do mouse está atualmente na área de cliente do controle.",
  },
  {
    name: "Padding",
    kind: "property",
    type: "TMargins",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Padding interno do controle.",
  },
  {
    name: "ParentDoubleBuffered",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Faz a propriedade DoubleBuffered deste componente seguir o valor do parent.",
  },
  {
    name: "ParentWindow",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Referência ao controle subjacente do parent.",
  },
  {
    name: "Showing",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Indica se o controle está sendo exibido na tela.",
  },
  {
    name: "TabOrder",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Posição do controle na ordem de tabulação do parent.",
  },
  {
    name: "TabStop",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Determina se o usuário pode focar este controle usando a tecla TAB.",
  },
  {
    name: "UseDockManager",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Se o docking manager é usado em operações drag-and-dock.",
  },
  {
    name: "VisibleDockClientCount",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Quantidade de controles visíveis encaixados neste controle.",
  },

  // ───────── Methods ─────────
  {
    name: "Broadcast",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Message", type: "Variant", isByRef: true, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Envia uma mensagem para cada um dos controles filhos.",
  },
  {
    name: "CanFocus",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Indica se o controle pode receber foco.",
  },
  {
    name: "ContainsControl",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Control", type: "TControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description:
      "Indica se um controle específico existe dentro deste controle (em qualquer nível de aninhamento).",
  },
  {
    name: "ControlAtPos",
    kind: "method",
    type: "TControl",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description:
      "Retorna o controle filho localizado em uma posição específica dentro do controle.",
  },
  {
    name: "DisableAlign",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Desabilita o realinhamento dos controles filhos.",
  },
  {
    name: "EnableAlign",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description:
      "Decrementa o contador incrementado por DisableAlign, eventualmente realinhando os controles filhos.",
  },
  {
    name: "FindChildControl",
    kind: "method",
    type: "TControl",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "ControlName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Retorna um controle filho dado seu nome.",
  },
  {
    name: "FlipChildren",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AllLevels", type: "Boolean", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Reverte as posições dos controles filhos.",
  },
  {
    name: "Focused",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Determina se o controle tem foco de entrada.",
  },
  {
    name: "HandleAllocated",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Reporta se existe handle Windows para o controle.",
  },
  {
    name: "HandleNeeded",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Cria um handle Windows para o controle se ainda não existir.",
  },
  {
    name: "InsertControl",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AControl", type: "TControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Insere um controle na propriedade Controls.",
  },
  {
    name: "PaintTo",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Desenha o controle (windowed) em um device context.",
  },
  {
    name: "Realign",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Força o controle a realinhar os filhos.",
  },
  {
    name: "RemoveControl",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AControl", type: "TControl", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Remove um controle específico do array Controls.",
  },
  {
    name: "ScaleBy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "M", type: "Integer", isByRef: false, isOptional: false },
      { name: "D", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Redimensiona o controle e seus filhos.",
  },
  {
    name: "ScrollBy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "DeltaX", type: "Integer", isByRef: false, isOptional: false },
      { name: "DeltaY", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Rola o conteúdo do controle.",
  },
  {
    name: "SetFocus",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Dá o foco de entrada para o controle.",
  },

  // ───────── Events (teclado — requerem janela própria) ─────────
  {
    name: "OnKeyDown",
    kind: "property",
    type: "TKeyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Ocorre quando o usuário pressiona uma tecla com o controle em foco.",
  },
  {
    name: "OnKeyUp",
    kind: "property",
    type: "TKeyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Ocorre quando o usuário solta uma tecla com o controle em foco.",
  },
  {
    name: "OnKeyPress",
    kind: "property",
    type: "TKeyPressEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TWinControl",
    description: "Ocorre quando o usuário pressiona uma tecla imprimível com o controle em foco.",
  },
];
