import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Imagem",
    kind: "class",
    type: "Imagem",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Forms",
    inheritsFrom: "TGraphicControl",
    description:
      "Componente gráfico para exibição de imagens (bitmap, JPEG, PNG, ICO, etc.) e desenhos em tela. Wrapper sobre TImage do Delphi — sem janela própria, renderiza no Canvas do pai.",
  },

  // ───────── Properties (TImage-specific) ─────────
  {
    name: "Picture",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: true,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Imagem exibida pelo controle (TPicture).",
  },
  {
    name: "Canvas",
    kind: "property",
    type: "TCanvas",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Superfície de desenho do componente gráfico.",
  },
  {
    name: "Center",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Se a imagem é centralizada quando ela é menor que o controle.",
  },
  {
    name: "Proportional",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Se a imagem mantém a proporção quando redimensionada (com Stretch ativo).",
  },
  {
    name: "Stretch",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Se a imagem é redimensionada para preencher o controle.",
  },
  {
    name: "Transparent",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Se o fundo da imagem é renderizado de forma transparente.",
  },
  {
    name: "IncrementalDisplay",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description:
      "Se a imagem é renderizada incrementalmente durante o carregamento (útil para imagens grandes).",
  },

  // ───────── Events ─────────
  {
    name: "OnProgress",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description:
      "Ocorre periodicamente durante operações lentas que afetam a imagem (carregamento/conversão).",
  },
  {
    name: "LoadFromFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pFileName", type: "String", isByRef: false, isOptional: false }],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Carrega uma imagem a partir de um arquivo.",
  },
  {
    name: "LoadFromBase64",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pBase64", type: "String", isByRef: false, isOptional: false }],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Imagem",
    description: "Carrega uma imagem a partir de um base64.",
  }
];
