import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "PageControl",
    kind: "class",
    type: "PageControl",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Forms",
    inheritsFrom: "TCustomControl",
    description:
      "Container de abas (TabSheets) — wrapper sobre o TRzPageControl da Raize. Permite alternar entre múltiplas páginas filhas.",
  },

  // ───────── Properties ─────────
  {
    name: "ActivePageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Obtem e define a tabsheet ativa no PageControl.",
  },
  {
    name: "PageCount",
    kind: "property",
    isReadOnly: true,
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Obtem o número de tabsheets no PageControl.",
  },
  {
    name: "ShowShadow",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Determina se exibe sombra no controle de abas.",
  },
  {
    name: "TabIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Índice da aba ativa.",
  },
  {
    name: "ShowCardFrame",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Exibe ou oculta a moldura do card.",
  },

  {
    name: "Color",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Define ou obtém a cor de fundo do controle",
  },

  {
    name: "BackgroundColor",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "PageControl",
    description: "Define ou obtem a cor de fundo do controle",
  },

];
