import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Color",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "StaticText",
    description: "Cor do texto.",
  },
  {
    name: "Caption",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "StaticText",
    description: "Texto exibido no componente.",
  },
  {
    name: "AutoSize",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "StaticText",
    description: "Determina se o componente redimensiona automaticamente de acordo com o texto.",
  },
  {
    name: "WordWrap",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "StaticText",
    description: "Especifica se o texto deve quebrar linhas caso ultrapasse a largura do controle.",
  },
  {
    name: "Alignment",
    kind: "property",
    type: "TAlignment",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "StaticText",
    description: "Alinhamento horizontal do texto.",
  },
  {
    name: "StaticText",
    kind: "class",
    type: "StaticText",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Forms",
    inheritsFrom: "TWinControl",
    description: "Componente que exibe um texto estático ou rótulo (Label).",
  },
];
