import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TabSheet",
    kind: "class",
    type: "TabSheet",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Forms",
    inheritsFrom: "TCustomControl",
    description:
      "Página/aba individual dentro de um PageControl. Wrapper sobre TRzTabSheet/TTabSheet (Vcl.ComCtrls).",
  },

  // ───────── Properties ─────────
  {
    name: "Highlighted",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Indica se a aba aparece destacada visualmente.",
  },
  {
    name: "ImageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Índice da imagem exibida na aba (referenciando o ImageList do PageControl).",
  },
  {
    name: "PageControl",
    kind: "property",
    type: "PageControl",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Referência ao PageControl que contém esta aba.",
  },
  {
    name: "PageIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Índice da aba na lista de todas as abas mantida pelo PageControl.",
  },
  {
    name: "TabIndex",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Posição da aba no conjunto de abas visíveis do PageControl (TPageControl).",
  },
  {
    name: "TabVisible",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Se a aba aparece (ou está oculta) no PageControl.",
  },
  {
    name: "Caption",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Texto exibido no rótulo da aba.",
  },
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Texto/Caption exibido na aba.",
  },

  // ───────── Events ─────────
  {
    name: "OnHide",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Ocorre quando a propriedade TabVisible muda para False.",
  },
  {
    name: "OnShow",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TabSheet",
    description: "Ocorre quando a propriedade TabVisible muda para True.",
  },
];
