import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TControl",
    kind: "class",
    type: "TControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TComponent",
    description:
      "Classe base de todo controle visual da VCL Delphi. Define posição, dimensão, alinhamento, visibilidade, fonte, ancoramento, hint e eventos de mouse/teclado/toque.",
  },

  // ───────── Properties ─────────
  {
    name: "Align",
    kind: "property",
    type: "TAlign",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Como o controle se alinha dentro de seu container (parent control).",
  },
  {
    name: "AlignWithMargins",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Se o controle deve ser restringido pelas suas margens.",
  },
  {
    name: "Anchors",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Como o controle se ancora ao seu parent (akLeft, akTop, akRight, akBottom).",
  },
  {
    name: "BiDiMode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Modo bidirecional do controle (suporte a idiomas RTL).",
  },
  {
    name: "BoundsRect",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Retângulo de limites do controle, no sistema de coordenadas do parent.",
  },
  {
    name: "ClientHeight",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Altura da área de cliente do controle em pixels.",
  },
  {
    name: "ClientOrigin",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Coordenadas de tela (em pixels) do canto superior esquerdo da área de cliente.",
  },
  {
    name: "ClientRect",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Retângulo da área de cliente do controle em pixels.",
  },
  {
    name: "ClientWidth",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Largura da área de cliente do controle em pixels.",
  },
  {
    name: "Constraints",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Restrições de tamanho (mínimo/máximo) do controle.",
  },
  {
    name: "ControlState",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Estado atual de um controle em tempo de execução.",
  },
  {
    name: "ControlStyle",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Características de estilo do controle.",
  },
  {
    name: "Cursor",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description:
      "Imagem usada para representar o ponteiro do mouse quando ele está sobre o controle.",
  },
  {
    name: "CustomHint",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Hint personalizado do controle.",
  },
  {
    name: "DockOrientation",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Como o controle é encaixado em relação a outros controles no mesmo parent.",
  },
  {
    name: "Enabled",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Controla se o controle responde a eventos de mouse, teclado e timer.",
  },
  {
    name: "ExplicitHeight",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Altura vertical explícita do controle em pixels.",
  },
  {
    name: "ExplicitLeft",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description:
      "Coordenada horizontal explícita da borda esquerda do componente relativo ao parent.",
  },
  {
    name: "ExplicitTop",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description:
      "Coordenada vertical explícita da borda superior do componente relativo ao parent.",
  },
  {
    name: "ExplicitWidth",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Largura horizontal explícita do controle em pixels.",
  },
  {
    name: "Floating",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Indica se o controle está flutuando.",
  },
  {
    name: "FloatingDockSiteClass",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Classe do controle temporário que hospeda o controle quando ele está flutuando.",
  },
  {
    name: "Height",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Tamanho vertical do controle em pixels.",
  },
  {
    name: "HelpContext",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Identificador numérico do tópico de Help para o controle.",
  },
  {
    name: "HelpKeyword",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Palavra-chave que identifica o tópico de Help para o controle.",
  },
  {
    name: "HelpType",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Se o Help context-sensitive é identificado por contexto ou por palavra-chave.",
  },
  {
    name: "Hint",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Texto exibido quando o usuário move o mouse sobre o controle.",
  },
  {
    name: "HostDockSite",
    kind: "property",
    type: "TWinControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Controle no qual este controle está encaixado.",
  },
  {
    name: "Left",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Coordenada horizontal da borda esquerda do componente relativo ao parent.",
  },
  {
    name: "LRDockWidth",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Largura do controle quando ele está encaixado horizontalmente.",
  },
  {
    name: "Margins",
    kind: "property",
    type: "TMargins",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Margens do controle.",
  },
  {
    name: "Parent",
    kind: "property",
    type: "TWinControl",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Parent do controle.",
  },
  {
    name: "ParentCustomHint",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Onde o controle busca seu hint personalizado.",
  },
  {
    name: "ShowHint",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Se exibe o Help Hint quando o mouse passa sobre o controle.",
  },
  {
    name: "StyleElements",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Elementos de estilo usados pelo controle.",
  },
  {
    name: "TBDockHeight",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Altura do controle quando ele está encaixado verticalmente.",
  },
  {
    name: "Top",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Coordenada Y do canto superior esquerdo do controle, relativa ao parent.",
  },
  {
    name: "Touch",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Componente touch manager associado ao controle.",
  },
  {
    name: "UndockHeight",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Altura do controle quando ele está flutuando.",
  },
  {
    name: "UndockWidth",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Largura do controle quando ele está flutuando.",
  },
  {
    name: "Visible",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Se o componente aparece na tela.",
  },
  {
    name: "Width",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Tamanho horizontal do controle ou formulário em pixels.",
  },

  // ───────── Methods ─────────
  {
    name: "BeginDrag",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Immediate", type: "Boolean", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Inicia o arrasto do controle.",
  },
  {
    name: "BringToFront",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Coloca o controle na frente de todos os outros controles no seu parent.",
  },
  {
    name: "ClientToParent",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Converte coordenadas client em coordenadas parent.",
  },
  {
    name: "ClientToScreen",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Converte um ponto de coordenadas client em coordenadas globais de tela.",
  },
  {
    name: "Dock",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Uso interno para encaixar o controle.",
  },
  {
    name: "Dragging",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Indica se o controle está sendo arrastado.",
  },
  {
    name: "EndDrag",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Drop", type: "Boolean", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Encerra o arrasto do controle.",
  },
  {
    name: "GetControlsAlignment",
    kind: "method",
    type: "TAlignment",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Indica como o texto é alinhado dentro do controle.",
  },
  {
    name: "GetTextBuf",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "Buffer", type: "String", isByRef: true, isOptional: false },
      { name: "BufSize", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description:
      "Recupera o texto do controle em um buffer e retorna a quantidade de caracteres copiados.",
  },
  {
    name: "GetTextLen",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Retorna o comprimento do texto do controle.",
  },
  {
    name: "Hide",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Torna o controle invisível.",
  },
  {
    name: "InitiateAction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description:
      "Chama o método Update do action link, se o controle estiver associado a um action link.",
  },
  {
    name: "Invalidate",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Repinta completamente o controle.",
  },
  {
    name: "IsRightToLeft",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Indica se o controle deve ser invertido da direita para a esquerda.",
  },
  {
    name: "ManualDock",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Encaixa o controle.",
  },
  {
    name: "ManualFloat",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Desencaixa o controle, deixando-o flutuante.",
  },
  {
    name: "Perform",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "Msg", type: "Integer", isByRef: false, isOptional: false },
      { name: "WParam", type: "Integer", isByRef: false, isOptional: false },
      { name: "LParam", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Responde como se o controle tivesse recebido uma mensagem Windows específica.",
  },
  {
    name: "Refresh",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Repinta o controle na tela.",
  },
  {
    name: "Repaint",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Força o controle a repintar sua imagem na tela.",
  },
  {
    name: "ScaleForPPI",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "NewPPI", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ajusta a escala do controle para o PPI (Pixels Per Inch) especificado.",
  },
  {
    name: "ScreenToClient",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Converte coordenadas de tela para coordenadas client.",
  },
  {
    name: "SendToBack",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Coloca o controle atrás de todos os outros controles.",
  },
  {
    name: "SetBounds",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "ALeft", type: "Integer", isByRef: false, isOptional: false },
      { name: "ATop", type: "Integer", isByRef: false, isOptional: false },
      { name: "AWidth", type: "Integer", isByRef: false, isOptional: false },
      { name: "AHeight", type: "Integer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Define Left, Top, Width e Height de uma só vez.",
  },
  {
    name: "SetTextBuf",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Buffer", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Define o texto do controle.",
  },
  {
    name: "Show",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Torna o controle visível.",
  },
  {
    name: "Update",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Processa imediatamente todas as mensagens de pintura pendentes.",
  },

  // ───────── Events ─────────
  {
    name: "OnClick",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário clica no controle.",
  },
  {
    name: "OnDblClick",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário dá um duplo-clique no controle.",
  },
  {
    name: "OnEnter",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o controle recebe o foco de entrada.",
  },
  {
    name: "OnExit",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o controle perde o foco de entrada.",
  },
  {
    name: "OnMouseDown",
    kind: "property",
    type: "TMouseEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário pressiona um botão do mouse sobre o controle.",
  },
  {
    name: "OnMouseUp",
    kind: "property",
    type: "TMouseEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário solta um botão do mouse sobre o controle.",
  },
  {
    name: "OnMouseMove",
    kind: "property",
    type: "TMouseEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário move o mouse sobre o controle.",
  },
  {
    name: "OnMouseEnter",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o ponteiro do mouse entra na área do controle.",
  },
  {
    name: "OnMouseLeave",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o ponteiro do mouse sai da área do controle.",
  },
  {
    name: "OnGesture",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário executa um gesto associado a este controle.",
  },
  {
    name: "OnMouseActivate",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o controle é ativado por clique do mouse.",
  },

  // ───────── Drag & drop ─────────
  {
    name: "OnDragDrop",
    kind: "property",
    type: "TDragDropEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário solta um objeto sendo arrastado sobre o controle.",
  },
  {
    name: "OnDragOver",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando um objeto está sendo arrastado sobre o controle.",
  },
  {
    name: "OnStartDock",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o usuário inicia o docking do controle.",
  },
  {
    name: "OnEndDock",
    kind: "property",
    type: "TEndDragEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando o docking termina (sucesso ou cancelamento).",
  },
  {
    name: "OnUnDock",
    kind: "property",
    type: "TUnDockEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando um controle filho deixa de estar docked.",
  },
  {
    name: "OnDockDrop",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre quando um cliente é docked neste controle.",
  },
  {
    name: "OnDockOver",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Ocorre enquanto um cliente está sendo arrastado para docking neste controle.",
  },
  {
    name: "OnGetSiteInfo",
    kind: "property",
    type: "TGetSiteInfoEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Permite informar dimensões/aceitação ao avaliar este controle como dock site.",
  },

  // ───────── Layout / align ─────────
  {
    name: "OnAlignInsertBefore",
    kind: "property",
    type: "TAlignInsertBeforeEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Determina a ordem entre dois controles ao usar Align.",
  },
  {
    name: "OnAlignPosition",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Permite customizar a posição final do controle durante o alinhamento.",
  },
  {
    name: "OnCanResize",
    kind: "property",
    type: "TCanResizeEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Disparado antes do redimensionamento para autorizar a operação.",
  },
  {
    name: "OnConstrainedResize",
    kind: "property",
    type: "TConstrainedResizeEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Disparado para limitar dinamicamente as dimensões durante o redimensionamento.",
  },
  {
    name: "OnContextPopup",
    kind: "property",
    type: "TContextPopupEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Disparado antes da exibição do menu popup de contexto.",
  },
  {
    name: "OnHelp",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Disparado quando o usuário solicita ajuda contextual sobre o controle.",
  },
  {
    name: "OnShortCut",
    kind: "property",
    type: "TMethod",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TControl",
    description: "Disparado quando uma combinação de teclas (atalho) é pressionada.",
  },
];
