import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TCustomEdit",
    kind: "class",
    type: "TCustomEdit",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TWinControl",
    description:
      "Classe base VCL (`Vcl.StdCtrls.TCustomEdit`) de todos os controles de edição textual nativos do Windows — TEdit, TMaskEdit, TMemo, TButtonedEdit, etc. Adiciona Text, ReadOnly, MaxLength, seleção e operações de clipboard sobre TWinControl.",
  },

  // ───────── Properties ─────────
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Texto exibido e editado no controle.",
  },
  {
    name: "TextHint",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Texto exibido como placeholder quando o controle está vazio.",
  },
  {
    name: "ReadOnly",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se o edit é somente leitura — usuário pode selecionar/copiar mas não modificar.",
  },
  {
    name: "MaxLength",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Número máximo de caracteres permitidos (0 = sem limite).",
  },
  {
    name: "PasswordChar",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Caractere usado para mascarar a digitação (ex: '*' para campos de senha).",
  },
  {
    name: "CharCase",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Caixa do texto (ecNormal=0, ecUpperCase=1, ecLowerCase=2).",
  },
  {
    name: "AutoSelect",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se todo o texto é selecionado automaticamente quando o controle recebe foco.",
  },
  {
    name: "AutoSize",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se a altura do controle se ajusta automaticamente para acomodar a fonte.",
  },
  {
    name: "Alignment",
    kind: "property",
    type: "TAlignment",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Alinhamento horizontal do texto dentro do edit.",
  },
  {
    name: "BorderStyle",
    kind: "property",
    type: "TBorderStyle",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se o edit tem borda (bsSingle) ou não (bsNone).",
  },
  {
    name: "Modified",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description:
      "Indica se o conteúdo foi modificado pelo usuário desde a última atribuição/save (dirty flag).",
  },
  {
    name: "NumbersOnly",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se o edit aceita apenas caracteres numéricos.",
  },
  {
    name: "OEMConvert",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description:
      "Se o texto é convertido entre ANSI e OEM ao perder o foco (compatibilidade com DOS).",
  },
  {
    name: "ParentColor",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Se o edit usa a cor de fundo do parent.",
  },
  {
    name: "SelStart",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Posição inicial (caractere) da seleção.",
  },
  {
    name: "SelLength",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Comprimento da seleção em caracteres.",
  },
  {
    name: "SelText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Texto atualmente selecionado.",
  },
  {
    name: "CanUndo",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Indica se há alterações que podem ser desfeitas (Undo).",
  },

  // ───────── Methods ─────────
  {
    name: "Clear",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Apaga todo o texto do edit.",
  },
  {
    name: "ClearSelection",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Remove a porção selecionada do texto.",
  },
  {
    name: "CopyToClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Copia a seleção atual para a área de transferência.",
  },
  {
    name: "CutToClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Recorta a seleção atual para a área de transferência.",
  },
  {
    name: "PasteFromClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Cola o conteúdo da área de transferência na posição atual do cursor.",
  },
  {
    name: "SelectAll",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Seleciona todo o texto do edit.",
  },
  {
    name: "Undo",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Desfaz a última alteração no texto.",
  },
  {
    name: "ClearUndo",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description: "Limpa o histórico de Undo.",
  },

  // ───────── Events ─────────
  {
    name: "OnChange",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TCustomEdit",
    description:
      "Ocorre quando o texto do edit muda (depois de cada caractere digitado ou atribuição via Text).",
  },
];
