import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TcxCustomEdit",
    kind: "class",
    type: "TcxCustomEdit",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Forms",
    inheritsFrom: "TCustomControl",
    description:
      "Base da família DevExpress (cx*) de editores. Toda a família ExpressEditors herda TcxCustomEdit que implementa funcionalidade base de editor — estilos, repository items, validação, eventos de edição e operações de clipboard.",
  },

  // ───────── Appearance ─────────
  {
    name: "Style",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações de aparência do editor no estado normal.",
  },
  {
    name: "StyleDisabled",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações de aparência do editor no estado desabilitado.",
  },
  {
    name: "StyleFocused",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações de aparência do editor com foco.",
  },
  {
    name: "StyleHot",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações de aparência do editor no estado hot (hover).",
  },
  {
    name: "StyleReadOnly",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações de aparência do editor em modo somente leitura.",
  },
  {
    name: "Styles",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Acesso aos estilos individuais aplicados ao editor em estados diferentes.",
  },
  {
    name: "Transparent",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Se o editor é transparente em modo GDI.",
  },

  // ───────── Content-Related ─────────
  {
    name: "CanSmartPaste",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Identifica se o editor suporta operações de Smart Paste (AI-powered).",
  },
  {
    name: "EditValue",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Valor de edição do componente (independente do tipo de display).",
  },
  {
    name: "Clear",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Limpa o editor.",
  },
  {
    name: "CopyToClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Copia o conteúdo selecionado para a área de transferência.",
  },
  {
    name: "CutToClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Recorta o conteúdo selecionado para a área de transferência.",
  },
  {
    name: "PasteFromClipboard",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Cola o conteúdo da área de transferência no editor.",
  },
  {
    name: "ResetEditValue",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Restaura o valor de edição anterior antes da alteração pendente ser aplicada.",
  },
  {
    name: "SelectAll",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Seleciona todo o conteúdo do editor.",
  },
  {
    name: "ValidateEdit",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Valida o display value do editor.",
  },

  // ───────── Data Binding ─────────
  {
    name: "DataBinding",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Permite vincular o editor a uma fonte de dados.",
  },
  {
    name: "CanPostEditValue",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Identifica se o editor data-aware pode persistir o valor no dataset vinculado.",
  },
  {
    name: "PostEditValue",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Persiste o valor de edição no dataset vinculado.",
  },

  // ───────── Settings / Repository ─────────
  {
    name: "ActiveProperties",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Acesso às configurações atuais do editor, independente da origem (read-only).",
  },
  {
    name: "Properties",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Configurações específicas do editor (quando não há RepositoryItem atribuído).",
  },
  {
    name: "RepositoryItem",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Repository item externo (TcxEditRepositoryItem) como fonte de configurações. Tem prioridade sobre Properties.",
  },
  {
    name: "GetPropertiesClass",
    kind: "method",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Retorna o tipo (classe) das configurações reais do editor.",
  },

  // ───────── General-Purpose ─────────
  {
    name: "AutoSize",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Se o editor redimensiona automaticamente para acomodar o conteúdo.",
  },
  {
    name: "CanModify",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Identifica se o editor está em modo somente leitura.",
  },
  {
    name: "IsEditValidating",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Indica se o editor está em processo de validação.",
  },
  {
    name: "IsHiding",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Indica se o editor está sendo ocultado.",
  },
  {
    name: "IsPosting",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Indica se o editor está persistindo seu valor para o dataset vinculado.",
  },
  {
    name: "SupportsSpelling",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Identifica se o editor suporta verificação ortográfica.",
  },

  // ───────── DevExpress runtime state ─────────
  {
    name: "EditModified",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Indica se o conteúdo do editor foi modificado pelo usuário desde a última atribuição/post (dirty flag). Atribua False para resetar.",
  },
  {
    name: "IsFocused",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Identifica se o editor (ou um de seus subcomponentes internos) está com o foco.",
  },
  {
    name: "ReadOnly",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Se o editor é somente leitura — usuário pode focar/copiar mas não modificar o valor.",
  },
  {
    name: "Text",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Texto/Caption exibido no editor.",
  },
  // ───────── Data7-specific (wrapper sobre Properties.HelpId/Hint do Data7) ─────────
  {
    name: "Ajuda",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Texto de ajuda (help-id) padrão Data7 associado ao editor. Exibido em popups de F1/contextuais.",
  },

  // ───────── Events ─────────
  {
    name: "OnEditing",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description: "Permite impedir que usuários ativem o editor (validação prévia).",
  },
  {
    name: "OnPostEditValue",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Executa código customizado quando o editor persiste o valor no dataset vinculado.",
  },
  {
    name: "OnFocusChanged",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Ocorre quando IsFocused muda — útil quando o editor abre subcomponentes que recebem foco (dropdown, calculadora, calendário).",
  },
  {
    name: "OnChange",
    kind: "property",
    type: "TNotifyEvent",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TcxCustomEdit",
    description:
      "Ocorre quando o valor do editor muda (texto digitado, item selecionado, checkbox alternado, etc.).",
  },
];
