import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TEditorType",
    kind: "class",
    type: "TEditorType",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description:
      "Tipo de editor inline usado por uma célula do Grid (TAdvStringGrid). Define como o usuário edita o conteúdo da célula.",
  },

  // ───────── Constantes (47 valores) ─────────
  {
    name: "edNormal",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit inline padrão (0).",
  },
  {
    name: "edSpinEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Spin edit (campo numérico com setas up/down).",
  },
  {
    name: "edComboEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Combobox editável (2).",
  },
  {
    name: "edComboList",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Combobox não-editável (3).",
  },
  {
    name: "edEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com botão lateral (4).",
  },
  {
    name: "edMaskEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com máscara e botão lateral (43).",
  },
  {
    name: "edCheckBox",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Checkbox (5).",
  },
  {
    name: "edDateEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "DatePicker (6).",
  },
  {
    name: "edDateTimeEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit de data e hora combinadas (28).",
  },
  {
    name: "edDateEditUpDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit de data com botões up/down.",
  },
  {
    name: "edTimeEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit de hora (8).",
  },
  {
    name: "edButton",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Botão (9).",
  },
  {
    name: "edDataCheckBox",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Checkbox cujo valor depende do texto da célula.",
  },
  {
    name: "edNumeric",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit numérico (com sinal) (11).",
  },
  {
    name: "edPositiveNumeric",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit numérico sem sinal (apenas valores positivos).",
  },
  {
    name: "edFloat",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit que aceita apenas ponto flutuante.",
  },
  {
    name: "edCapital",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit que converte todas as letras digitadas para maiúsculas.",
  },
  {
    name: "edMixedCase",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com capitalização automática da primeira letra.",
  },
  {
    name: "edPassword",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit no modo senha — texto mascarado (16).",
  },
  {
    name: "edUnitEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com seleção de unidade e botão lateral.",
  },
  {
    name: "edLowerCase",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit que converte todas as letras digitadas para minúsculas.",
  },
  {
    name: "edUpperCase",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit que converte todas as letras digitadas para maiúsculas.",
  },
  {
    name: "edFloatSpinEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Spin edit de ponto flutuante.",
  },
  {
    name: "edTimeSpinEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Spin edit de hora.",
  },
  {
    name: "edDateSpinEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Spin edit de data.",
  },
  {
    name: "edNumericEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit numérico com botão lateral.",
  },
  {
    name: "edFloatEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit de ponto flutuante com botão lateral.",
  },
  {
    name: "edCustom",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Editor customizado (ver tópicos avançados de edição) (25).",
  },
  {
    name: "edRichEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Rich text editor.",
  },
  {
    name: "edUniEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit Unicode.",
  },
  {
    name: "edUniEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit Unicode com botão lateral.",
  },
  {
    name: "edUniComboEdit",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Combobox Unicode editável.",
  },
  {
    name: "edUniComboList",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Combobox Unicode não-editável.",
  },
  {
    name: "edUniMemo",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Memo Unicode multilinha.",
  },
  {
    name: "edValidChars",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description:
      "Aceita apenas caracteres pertencentes ao conjunto de Grid.ValidChars ou Grid.ValidCharSet.",
  },
  {
    name: "edCalculatorDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com calculadora dropdown (32).",
  },
  {
    name: "edTrackBarDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit numérico com trackbar dropdown para selecionar valor inteiro.",
  },
  {
    name: "edColorPickerDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description:
      "Color picker com 3 métodos de seleção (dropdown list, color cube, color spectrum).",
  },
  {
    name: "edImagePickerDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Image picker inline (37).",
  },
  {
    name: "edMemoDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com memo dropdown (31).",
  },
  {
    name: "edDetailDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Combobox onde cada item tem imagem + caption + notas (34).",
  },
  {
    name: "edGridDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com Grid dropdown — valor é selecionado da grade (35).",
  },
  {
    name: "edGridExDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com Grid estendido como dropdown (38).",
  },
  {
    name: "edTimePickerDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Inline com relógio dropdown para selecionar hora.",
  },
  {
    name: "edControlDropDown",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit com controle customizado como dropdown (39).",
  },
  {
    name: "edNumericUnitEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit numérico com seleção de unidade e botão lateral.",
  },
  {
    name: "edFloatUnitEditBtn",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Edit de ponto flutuante com seleção de unidade e botão lateral.",
  },
  {
    name: "edNone",
    kind: "variable",
    type: "TEditorType",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Sem editor — célula não-editável (27).",
  },
];
