import type { SystemSymbolInfo } from "../types";
import { defineEnum } from "../symbol-helpers";

export const symbols: SystemSymbolInfo[] = defineEnum({
  name: "TEditorType",
  containerName: "Forms",
  description:
    "Tipo de editor inline usado por uma célula do Grid (TAdvStringGrid). Define como o usuário edita o conteúdo da célula.",
  values: [
    ["edNormal", "Edit inline padrão (0)."],
    ["edSpinEdit", "Spin edit (campo numérico com setas up/down)."],
    ["edComboEdit", "Combobox editável (2)."],
    ["edComboList", "Combobox não-editável (3)."],
    ["edEditBtn", "Edit com botão lateral (4)."],
    ["edMaskEditBtn", "Edit com máscara e botão lateral (43)."],
    ["edCheckBox", "Checkbox (5)."],
    ["edDateEdit", "DatePicker (6)."],
    ["edDateTimeEdit", "Edit de data e hora combinadas (28)."],
    ["edDateEditUpDown", "Edit de data com botões up/down."],
    ["edTimeEdit", "Edit de hora (8)."],
    ["edButton", "Botão (9)."],
    ["edDataCheckBox", "Checkbox cujo valor depende do texto da célula."],
    ["edNumeric", "Edit numérico (com sinal) (11)."],
    ["edPositiveNumeric", "Edit numérico sem sinal (apenas valores positivos)."],
    ["edFloat", "Edit que aceita apenas ponto flutuante."],
    ["edCapital", "Edit que converte todas as letras digitadas para maiúsculas."],
    ["edMixedCase", "Edit com capitalização automática da primeira letra."],
    ["edPassword", "Edit no modo senha — texto mascarado (16)."],
    ["edUnitEditBtn", "Edit com seleção de unidade e botão lateral."],
    ["edLowerCase", "Edit que converte todas as letras digitadas para minúsculas."],
    ["edUpperCase", "Edit que converte todas as letras digitadas para maiúsculas."],
    ["edFloatSpinEdit", "Spin edit de ponto flutuante."],
    ["edTimeSpinEdit", "Spin edit de hora."],
    ["edDateSpinEdit", "Spin edit de data."],
    ["edNumericEditBtn", "Edit numérico com botão lateral."],
    ["edFloatEditBtn", "Edit de ponto flutuante com botão lateral."],
    ["edCustom", "Editor customizado (ver tópicos avançados de edição) (25)."],
    ["edRichEdit", "Rich text editor."],
    ["edUniEdit", "Edit Unicode."],
    ["edUniEditBtn", "Edit Unicode com botão lateral."],
    ["edUniComboEdit", "Combobox Unicode editável."],
    ["edUniComboList", "Combobox Unicode não-editável."],
    ["edUniMemo", "Memo Unicode multilinha."],
    [
      "edValidChars",
      "Aceita apenas caracteres pertencentes ao conjunto de Grid.ValidChars ou Grid.ValidCharSet.",
    ],
    ["edCalculatorDropDown", "Edit com calculadora dropdown (32)."],
    ["edTrackBarDropDown", "Edit numérico com trackbar dropdown para selecionar valor inteiro."],
    [
      "edColorPickerDropDown",
      "Color picker com 3 métodos de seleção (dropdown list, color cube, color spectrum).",
    ],
    ["edImagePickerDropDown", "Image picker inline (37)."],
    ["edMemoDropDown", "Edit com memo dropdown (31)."],
    ["edDetailDropDown", "Combobox onde cada item tem imagem + caption + notas (34)."],
    ["edGridDropDown", "Edit com Grid dropdown — valor é selecionado da grade (35)."],
    ["edGridExDropDown", "Edit com Grid estendido como dropdown (38)."],
    ["edTimePickerDropDown", "Inline com relógio dropdown para selecionar hora."],
    ["edControlDropDown", "Edit com controle customizado como dropdown (39)."],
    ["edNumericUnitEditBtn", "Edit numérico com seleção de unidade e botão lateral."],
    ["edFloatUnitEditBtn", "Edit de ponto flutuante com seleção de unidade e botão lateral."],
    ["edNone", "Sem editor — célula não-editável (27)."],
  ],
});
