import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TShiftState",
    kind: "class",
    type: "TShiftState",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description:
      "Indica o estado das teclas modificadoras, botões do mouse ou dispositivos touch. Usado por handlers de eventos de teclado e mouse para detectar combinações no momento do evento. É um conjunto (set) de valores ssXxx (vários podem estar ativos simultaneamente).",
  },

  // ───────── Constantes ─────────
  {
    name: "ssShift",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "A tecla SHIFT está pressionada.",
  },
  {
    name: "ssAlt",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "A tecla ALT está pressionada.",
  },
  {
    name: "ssCtrl",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "A tecla CTRL está pressionada.",
  },
  {
    name: "ssLeft",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Botão esquerdo do mouse está pressionado.",
  },
  {
    name: "ssRight",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Botão direito do mouse está pressionado.",
  },
  {
    name: "ssMiddle",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Botão central (scroll) do mouse está pressionado.",
  },
  {
    name: "ssDouble",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "O botão do mouse recebeu um duplo-clique.",
  },
  {
    name: "ssTouch",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "O usuário está mantendo o dedo sobre a superfície touch.",
  },
  {
    name: "ssPen",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "A caneta (stylus) está tocando a superfície de um tablet.",
  },
  {
    name: "ssCommand",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "A tecla CMD está pressionada (apenas no macOS).",
  },
  {
    name: "ssHorizontal",
    kind: "variable",
    type: "TShiftState",
    isShared: true,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "Forms",
    description: "Movimento horizontal no touch ou wheel produzindo deslocamento horizontal.",
  },
];
