import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "ValueTextBox",
    kind: "class",
    type: "ValueTextBox",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "Forms",
    inheritsFrom: "TcxCustomTextEdit",
    description:
      "Caixa de texto especializada em valores monetários (TValorEditor). Wrapper sobre TcxCurrencyEdit.",
  },

  // ───────── Properties (formatação numérica) ─────────
  {
    name: "DecimalPlaces",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Quantidade de casas decimais exibidas (e aceitas) pelo editor de valor.",
  },
  {
    name: "DisplayFormat",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Máscara de formatação para exibição do valor (ex.: 'R$ #,##0.00').",
  },
  {
    name: "MinValue",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Valor mínimo aceito pelo editor (0 = sem mínimo).",
  },
  {
    name: "MaxValue",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Valor máximo aceito pelo editor (0 = sem máximo).",
  },
  {
    name: "AsInteger",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Valor atual convertido para Integer (truncado).",
  },
  {
    name: "AsFloat",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Valor atual como Double (ponto flutuante).",
  },
  {
    name: "Value",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "ValueTextBox",
    description: "Valor numérico atual no editor.",
  },
];
