import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "File",
    kind: "class",
    type: "IO.File",
    isShared: true,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "IO",
    description: "Classe para manipulação de arquivos físicos.",
  },
  {
    name: "ExtractName",
    kind: "method",
    type: "String",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description: "Extrai o nome do arquivo de um caminho/patch.",
  },
  {
    name: "ExtractDir",
    kind: "method",
    type: "String",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description: "Extrai o caminho da pasta/diretório de um nome de arquivo/patch.",
  },
  {
    name: "Exists",
    kind: "method",
    type: "Boolean",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description: "Verifica se um arquivo existe.",
  },
  {
    name: "Delete",
    kind: "method",
    type: "Boolean",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description:
      "Exclui o arquivo especificado no parâmetro. É retornado um valor true sempre que o arquivo é excluído com sucesso.",
  },
  {
    name: "OpenFileDialog",
    kind: "method",
    type: "String",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pTitle",
        type: "String",
        isByRef: false,
        isOptional: true,
        defaultValue: '""',
      },
      {
        name: "pFilter",
        type: "String",
        isByRef: false,
        isOptional: true,
        defaultValue: '""',
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description:
      "Exibe uma caixa de diálogo para seleção de arquivo e retorna o caminho completo do arquivo selecionado.",
  },
  {
    name: "XlsToStringGrid",
    kind: "method",
    type: "Boolean",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pXlsPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pGrid",
        type: "Forms.Grid",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description:
      "Importa os dados de um arquivo .xls para uma Grid. É necessário ter o Excel instalado no computador que irá executar o projeto.",
  },
  {
    name: "Copy",
    kind: "method",
    type: "Boolean",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pSource",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pDest",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description: "Realiza a cópia de um arquivo.",
  },
  {
    name: "GetFiles",
    kind: "method",
    type: "Void",
    isShared: true,
    isPrivate: false,
    parameters: [
      {
        name: "pPath",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
      {
        name: "pList",
        type: "StringList",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description:
      "Preenche um objeto do tipo StringList com as pastas/arquivos do caminho especificado.",
  },
  {
    name: "ZipFile",
    kind: "class",
    type: "IO.File.ZipFile",
    isShared: true,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "File",
    description: "Contém métodos para compactar e descompactar arquivos.",
  },
];
