import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "IXMLNodeList",
    kind: "class",
    type: "XML.IXMLNodeList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "XML",
    inheritsFrom: "TObject",
    description:
      "Lista ordenada de nós XML (IXMLNode). Permite navegação por índice e busca por nome.",
  },

  // ───────── Acesso por nome / índice ─────────
  {
    name: "FindNode",
    kind: "method",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "NodeName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Localiza e retorna o primeiro nó filho com o nome informado.",
  },
  {
    name: "Count",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Retorna a quantidade de nós contidos na lista.",
  },
  {
    name: "_GetNodes",
    kind: "method",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "I", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Acessor interno (getter) da propriedade indexada Nodes.",
  },
  {
    name: "Nodes",
    kind: "indexed-property",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "I", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Propriedade indexada que retorna o nó na posição especificada da lista.",
  },

  // ───────── IUnknown ─────────
  {
    name: "QueryInterface",
    kind: "method",
    type: "HRESULT",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "IID", type: "TGUID", isByRef: false, isOptional: false },
      { name: "Obj", type: "PVOID", isByRef: true, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Herdado de IUnknown — retorna outra interface implementada pela lista.",
  },
  {
    name: "_AddRef",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description: "Herdado de IUnknown — incrementa o contador de referências da interface.",
  },
  {
    name: "_Release",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "IXMLNodeList",
    description:
      "Herdado de IUnknown — decrementa o contador de referências; libera a instância ao chegar a zero.",
  },
];
