import type { SystemSymbolInfo } from "../types";

const UNSUP_NOTE =
  " Não traduzido pelo compilador Data7 — uso emite diagnóstico unsupported-member.";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TXMLDocument",
    kind: "class",
    type: "XML.TXMLDocument",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "XML",
    inheritsFrom: "TObject",
    description: "Representa um documento XML que pode ser lido, manipulado e salvo.",
  },

  // ───────── Properties ─────────
  {
    name: "Active",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Ativa ou desativa a manipulação do documento XML.",
  },
  {
    name: "ChildNodes",
    kind: "property",
    type: "XML.IXMLNodeList",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Lista de nós filhos diretos no documento XML.",
  },
  {
    name: "DocumentElement",
    kind: "property",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Nó raiz (elemento principal) do documento XML.",
  },
  {
    name: "Encoding",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Codificação do documento XML (ex.: UTF-8, ISO-8859-1).",
  },
  {
    name: "FileName",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Caminho/nome do arquivo XML físico.",
  },
  {
    name: "Node",
    kind: "property",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Nó base associado ao documento XML.",
  },
  {
    name: "Options",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Conjunto de opções de comportamento do parser/serializer." + UNSUP_NOTE,
    isUnsupported: true,
  },
  {
    name: "Version",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Versão declarada no prólogo XML (ex.: 1.0).",
  },
  {
    name: "XML",
    kind: "property",
    type: "TStrings",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Conteúdo bruto do XML em uma lista de strings (linhas).",
  },

  // ───────── Constructor overloads ─────────
  {
    name: "Create",
    kind: "method",
    type: "TXMLDocument",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AOwner", type: "TComponent", isByRef: false, isOptional: false }],
    overloads: [[]],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description:
      "Construtor. Aceita um Owner (TComponent) responsável pela liberação ou nenhum argumento (default).",
  },

  // ───────── Methods ─────────
  {
    name: "AddChild",
    kind: "method",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "TagName", type: "String", isByRef: false, isOptional: false },
      { name: "NamespaceURI", type: "String", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description:
      "Adiciona um novo nó raiz/filho no documento com a tag e (opcionalmente) o namespace informado.",
  },
  {
    name: "SaveToFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AFileName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Salva o conteúdo XML modificado no arquivo especificado.",
  },
  {
    name: "LoadFromFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "AFileName", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Carrega o documento XML a partir de um arquivo físico.",
  },

  // ───────── Acessores internos ─────────
  {
    name: "GetActive",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade Active.",
  },
  {
    name: "GetChildNodes",
    kind: "method",
    type: "XML.IXMLNodeList",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade ChildNodes.",
  },
  {
    name: "GetDocumentElement",
    kind: "method",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade DocumentElement.",
  },
  {
    name: "GetDocumentNode",
    kind: "method",
    type: "XML.IXMLNode",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Retorna o nó base (DocumentNode) associado ao documento XML.",
  },
  {
    name: "GetEncoding",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade Encoding.",
  },
  {
    name: "GetOptions",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade Options.",
  },
  {
    name: "GetVersion",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade Version.",
  },
  {
    name: "GetXML",
    kind: "method",
    type: "TStrings",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (getter) da propriedade XML.",
  },
  {
    name: "SetActive",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "Boolean", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade Active.",
  },
  {
    name: "SetDocumentElement",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "XML.IXMLNode", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade DocumentElement.",
  },
  {
    name: "SetEncoding",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "Variant", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade Encoding." + UNSUP_NOTE,
    isUnsupported: true,
  },
  {
    name: "SetOptions",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "Variant", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade Options." + UNSUP_NOTE,
    isUnsupported: true,
  },
  {
    name: "SetVersion",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "Variant", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade Version." + UNSUP_NOTE,
    isUnsupported: true,
  },
  {
    name: "SetXML",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Value", type: "TStrings", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TXMLDocument",
    description: "Acessor interno (setter) da propriedade XML.",
  },
];
