export interface SugarUtility {
  readonly id: string;
  readonly namespace: string;
  readonly dependencies: readonly string[];
  generateCode(): string;
}

export class SugarRegistry {
  private static readonly registry = new Map<string, SugarUtility>();

  public static register(utility: SugarUtility): void {
    this.registry.set(utility.id, utility);
  }

  public static get(id: string): SugarUtility | undefined {
    return this.registry.get(id);
  }

  public static getAll(): SugarUtility[] {
    return Array.from(this.registry.values());
  }

  public static resolveDependencies(usedSugarIds: Iterable<string>): Set<string> {
    const resolved = new Set<string>();
    const queue = Array.from(usedSugarIds);
    while (queue.length > 0) {
      const current = queue.shift()!;
      if (resolved.has(current)) continue;
      resolved.add(current);
      const sugar = this.get(current);
      if (sugar && sugar.dependencies) {
        for (const dep of sugar.dependencies) {
          if (!resolved.has(dep)) {
            queue.push(dep);
          }
        }
      }
    }
    return resolved;
  }
}

// Register Enum Sugar Utility
SugarRegistry.register({
  id: "enum",
  namespace: "core_sugars_enum",
  dependencies: ["list"], // core_sugars_enum depends on core_sugars_list
  generateCode() {
    return [
      "Namespace core_sugars_enum",
      "Class CoreSugarBaseEnum",
      "   Inherits BaseEnum",
      "   Sub New()",
      "      MyBase.New()",
      "   End Sub",
      "   Sub Free()",
      "      MyBase.Free()",
      "   End Sub",
      "End Class",
      "End Namespace"
    ].join("\r\n");
  }
});

// Register List Sugar Utility
SugarRegistry.register({
  id: "list",
  namespace: "core_sugars_list",
  dependencies: [],
  generateCode() {
    return [
      "Namespace core_sugars_list",
      "",
      "   Class CoreSugarBaseItem",
      "      Public Disposed As Boolean",
      "      Sub New()",
      "         MyBase.New()",
      "      End Sub",
      "      Overridable Sub Dispose()",
      "         me.Disposed = True",
      "      End Sub",
      "      Overridable Function GetID() As String",
      "         GetID = \"\"",
      "      End Function",
      "   End Class",
      "",
      "   Class CoreSugarValueWrapper",
      "      Inherits CoreSugarBaseItem",
      "      Public value As Variant",
      "      Sub New(pValue As Variant)",
      "         MyBase.New()",
      "         me.value = pValue",
      "      End Sub",
      "      Overrides Function GetID() As String",
      "         GetID = CStr(me.value)",
      "      End Function",
      "   End Class",
      "",
      "   Class CoreSugarObjectWrapper",
      "      Inherits CoreSugarBaseItem",
      "      Public value As TObject",
      "      Sub New(pValue As TObject)",
      "         MyBase.New()",
      "         me.value = pValue",
      "      End Sub",
      "      Overrides Sub Dispose()",
      "         If me.value <> NULL Then",
      "            me.value.Free()",
      "         End If",
      "         MyBase.Dispose()",
      "      End Sub",
      "   End Class",
      "",
      "   Class CoreSugarDateTimeWrapper",
      "      Inherits CoreSugarBaseItem",
      "      Public value As TDateTime",
      "      Sub New(pValue As TDateTime)",
      "         MyBase.New()",
      "         me.value = pValue",
      "      End Sub",
      "   End Class",
      "   Class CoreSugarHelper",
      "      Public Shared Function UnwrapPrimitive(pItem As CoreSugarBaseItem) As Variant",
      "         If pItem = NULL Then",
      "            UnwrapPrimitive = \"\"",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarValueWrapper = CType(pItem, CoreSugarValueWrapper)",
      "         If wrapper <> NULL Then",
      "            UnwrapPrimitive = wrapper.value",
      "         Else",
      "            UnwrapPrimitive = \"\"",
      "         End If",
      "      End Function",
      "",
      "      Public Shared Function UnwrapObject(pItem As CoreSugarBaseItem) As TObject",
      "         If pItem = NULL Then",
      "            UnwrapObject = NULL",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarObjectWrapper = CType(pItem, CoreSugarObjectWrapper)",
      "         If wrapper <> NULL Then",
      "            UnwrapObject = wrapper.value",
      "         Else",
      "            UnwrapObject = pItem",
      "         End If",
      "      End Function",
      "",
      "      Public Shared Function UnwrapDateTime(pItem As CoreSugarBaseItem) As TDateTime",
      "         If pItem = NULL Then",
      "            UnwrapDateTime = 0",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarDateTimeWrapper = CType(pItem, CoreSugarDateTimeWrapper)",
      "         If wrapper <> NULL Then",
      "            UnwrapDateTime = wrapper.value",
      "         Else",
      "            UnwrapDateTime = 0",
      "         End If",
      "      End Function",
      "   End Class",
      "",
      "   Delegate Function SugarFindDel(pValue As CoreSugarBaseItem, i As Integer, extra As Variant) As Boolean",
      "   Delegate Function SugarMapDel(pValue As CoreSugarBaseItem, i As Integer, extra As Variant) As CoreSugarBaseItem",
      "   Delegate Function SugarSortDel(pValue As CoreSugarBaseItem, i As Integer, extra As Variant) As String",
      "   Delegate Sub SugarForEachDel(pValue As CoreSugarBaseItem, i As Integer, extra As Variant)",
      "",
      "   Class CoreSugarBaseList",
      "      Protected _list As StringList",
      "      Protected _ownsObjects As Boolean",
      "",
      "      Sub New(pOwnsObjects As Boolean = True)",
      "         MyBase.New()",
      "         me._list = New StringList()",
      "         me._ownsObjects = pOwnsObjects",
      "         me._list.OwnsObjects = pOwnsObjects",
      "      End Sub",
      "",
      "      Property OwnsObjects As Boolean",
      "         Get",
      "            OwnsObjects = me._ownsObjects",
      "         End Get",
      "         Set(pValue As Boolean)",
      "            me._ownsObjects = pValue",
      "            me._list.OwnsObjects = pValue",
      "         End Set",
      "      End Property",
      "",
      "      Function Length() As Integer",
      "         Length = me._list.Count",
      "      End Function",
      "",
      "      Function Count() As Integer",
      "         Count = me._list.Count",
      "      End Function",
      "",
      "      Protected Sub ClearInternal(pDispose As Boolean = True)",
      "         If pDispose And me._ownsObjects Then",
      "            Dim i As Integer, _count As Integer = me._list.Count",
      "            For i = 0 To _count - 1",
      "               Dim obj As TObject = me._list.Objects(i)",
      "               If obj <> NULL Then",
      "                  Dim item As CoreSugarBaseItem = CType(obj, CoreSugarBaseItem)",
      "                  If item <> NULL Then",
      "                     item.Dispose()",
      "                  End If",
      "               End If",
      "            Next",
      "         End If",
      "         me._list.Clear()",
      "      End Sub",
      "",
      "      Protected Sub FreeInternal(pDispose As Boolean = True)",
      "         me.ClearInternal(pDispose)",
      "         me._list.Free()",
      "         MyBase.Free()",
      "      End Sub",
      "   End Class",
      "",
      "   Class CoreSugarList",
      "      Inherits CoreSugarBaseList",
      "",
      "      Sub New(pOwnsObjects As Boolean = True)",
      "         MyBase.New(pOwnsObjects)",
      "      End Sub",
      "",
      "      Overridable Function CreateInstance() As CoreSugarList",
      "         CreateInstance = New CoreSugarList(me.OwnsObjects)",
      "      End Function",
      "",
      "      Protected Function GetItemInternal(pIndex As Integer) As CoreSugarBaseItem",
      "         GetItemInternal = CType(me._list.Objects(pIndex), CoreSugarBaseItem)",
      "      End Function",
      "",
      "      Protected Sub SetItemInternal(pIndex As Integer, pValue As CoreSugarBaseItem)",
      "         me._list.Objects(pIndex) = pValue",
      "      End Sub",
      "",
      "      Protected Sub AddInternal(pValue As CoreSugarBaseItem)",
      "         me._list.AddObject(pValue.GetID(), pValue)",
      "      End Sub",
      "",
      "      Protected Sub InsertInternal(pIndex As Integer, pValue As CoreSugarBaseItem)",
      "         me._list.InsertObject(pIndex, pValue.GetID(), pValue)",
      "      End Sub",
      "",
      "      Function Push(pValue As CoreSugarBaseItem) As CoreSugarList",
      "         me.AddInternal(pValue)",
      "         Push = me",
      "      End Function",
      "",
      "      Sub Add(pValues As CoreSugarList)",
      "         Dim i As Integer, _count As Integer = pValues.Length()",
      "         For i = 0 To _count - 1",
      "            me.Push(pValues.GetItemInternal(i))",
      "         Next",
      "      End Sub",
      "",
      "      Function Pop() As CoreSugarBaseItem",
      "         Dim idx As Integer = me.Length() - 1",
      "         If idx >= 0 Then",
      "            Pop = me.GetItemInternal(idx)",
      "            Dim tempOwns As Boolean = me._list.OwnsObjects",
      "            me._list.OwnsObjects = False",
      "            me._list.Delete(idx)",
      "            me._list.OwnsObjects = tempOwns",
      "         Else",
      "            Pop = NULL",
      "         End If",
      "      End Function",
      "",
      "      Function Shift() As CoreSugarBaseItem",
      "         If me.Length() > 0 Then",
      "            Shift = me.GetItemInternal(0)",
      "            Dim tempOwns As Boolean = me._list.OwnsObjects",
      "            me._list.OwnsObjects = False",
      "            me._list.Delete(0)",
      "            me._list.OwnsObjects = tempOwns",
      "         Else",
      "            Shift = NULL",
      "         End If",
      "      End Function",
      "",
      "      Function Unshift(pValue As CoreSugarBaseItem) As CoreSugarList",
      "         me.InsertInternal(0, pValue)",
      "         Unshift = me",
      "      End Function",
      "",
      "      Function Filter(pHandler As SugarFindDel, extra As Variant) As CoreSugarList",
      "         Dim result As CoreSugarList = me.CreateInstance()",
      "         Dim i As Integer, _count As Integer = me.Length()",
      "         For i = 0 To _count - 1",
      "            Dim item As CoreSugarBaseItem = me.GetItemInternal(i)",
      "            If pHandler(item, i, extra) Then",
      "               result.Push(item)",
      "            End If",
      "         Next",
      "         result.OwnsObjects = False",
      "         Filter = result",
      "      End Function",
      "",
      "      Function Map(pHandler As SugarMapDel, extra As Variant) As CoreSugarList",
      "         Dim result As CoreSugarList = me.CreateInstance()",
      "         Dim i As Integer, _count As Integer = me.Length()",
      "         For i = 0 To _count - 1",
      "            result.Push(pHandler(me.GetItemInternal(i), i, extra))",
      "         Next",
      "         Map = result",
      "      End Function",
      "",
      "      Function ForEach(pHandler As SugarForEachDel, extra As Variant) As CoreSugarList",
      "         Dim i As Integer, _count As Integer = me.Length()",
      "         For i = 0 To _count - 1",
      "            pHandler(me.GetItemInternal(i), i, extra)",
      "         Next",
      "         ForEach = me",
      "      End Function",
      "",
      "      Function Slice(pStart As Integer, pCount As Integer) As CoreSugarList",
      "         Dim result As CoreSugarList = me.CreateInstance()",
      "         Dim _len As Integer = me.Length()",
      "         Dim i As Integer, idx As Integer",
      "         For i = 0 To pCount - 1",
      "            idx = pStart + i",
      "            If idx >= 0 And idx < _len Then",
      "               result.Push(me.GetItemInternal(idx))",
      "            End If",
      "         Next",
      "         result.OwnsObjects = False",
      "         Slice = result",
      "      End Function",
      "",
      "      Function Reverse() As CoreSugarList",
      "         Dim i As Integer, _len As Integer = me.Length()",
      "         Dim temp As StringList = New StringList()",
      "         For i = 0 To _len - 1",
      "            temp.AddObject(me._list.Strings(i), me._list.Objects(i))",
      "         Next",
      "         ",
      "         Dim tempOwns As Boolean = me._list.OwnsObjects",
      "         me._list.OwnsObjects = False",
      "         me.ClearInternal(False)",
      "         ",
      "         For i = 0 To _len - 1",
      "            Dim idx As Integer = _len - 1 - i",
      "            me._list.AddObject(temp.Strings(idx), temp.Objects(idx))",
      "         Next",
      "         ",
      "         me._list.OwnsObjects = tempOwns",
      "         temp.Free()",
      "         Reverse = me",
      "      End Function",
      "",
      "      Function Sort(pHandler As SugarSortDel, pAsc As Boolean, extra As Variant) As CoreSugarList",
      "         If pHandler <> NULL Then",
      "            Dim listTemp As StringList = New StringList()",
      "            Dim i As Integer, _len As Integer = me.Length()",
      "            For i = 0 To _len - 1",
      "               Dim item As CoreSugarBaseItem = me.GetItemInternal(i)",
      "               Dim key As String = pHandler(item, i, extra)",
      "               listTemp.AddObject(key, item)",
      "            Next",
      "            listTemp.Sorted = True",
      "            ",
      "            Dim tempOwns As Boolean = me._list.OwnsObjects",
      "            me._list.OwnsObjects = False",
      "            me.ClearInternal(False)",
      "            ",
      "            For i = 0 To _len - 1",
      "               Dim idx As Integer = i",
      "               If Not pAsc Then",
      "                  idx = _len - 1 - i",
      "               End If",
      "               me.AddInternal(CType(listTemp.Objects(idx), CoreSugarBaseItem))",
      "            Next",
      "            ",
      "            me._list.OwnsObjects = tempOwns",
      "            listTemp.Free()",
      "         End If",
      "         Sort = me",
      "      End Function",
      "",
      "      Sub Clean()",
      "         me.ClearInternal(True)",
      "      End Sub",
      "",
      "      Sub Dispose()",
      "         me.ClearInternal(True)",
      "      End Sub",
      "",
      "      Sub Free()",
      "         me.FreeInternal(True)",
      "      End Sub",
      "   End Class",
      "",
      "   Class CoreSugarListPrimitives",
      "      Inherits CoreSugarList",
      "",
      "      Sub New()",
      "         MyBase.New(True)",
      "      End Sub",
      "",
      "      Overrides Function CreateInstance() As CoreSugarList",
      "         CreateInstance = New CoreSugarListPrimitives()",
      "      End Function",
      "",
      "      Protected Function Wrap(pValue As Variant) As CoreSugarBaseItem",
      "         Wrap = New CoreSugarValueWrapper(pValue)",
      "      End Function",
      "",
      "      Protected Function Unwrap(pItem As CoreSugarBaseItem) As Variant",
      "         If pItem = NULL Then",
      "            Unwrap = \"\"",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarValueWrapper = CType(pItem, CoreSugarValueWrapper)",
      "         If wrapper <> NULL Then",
      "            Unwrap = wrapper.value",
      "         Else",
      "            Unwrap = \"\"",
      "         End If",
      "         ",
      "      End Function",
      "   End Class",
      "",
      "   Class CoreSugarListObjects",
      "      Inherits CoreSugarList",
      "",
      "      Sub New(pOwnsObjects As Boolean = True)",
      "         MyBase.New(pOwnsObjects)",
      "      End Sub",
      "",
      "      Overrides Function CreateInstance() As CoreSugarList",
      "         CreateInstance = New CoreSugarListObjects(me.OwnsObjects)",
      "      End Function",
      "",
      "      Protected Function Wrap(pObj As TObject) As CoreSugarBaseItem",
      "         If pObj = NULL Then",
      "            Wrap = NULL",
      "            Exit Function",
      "         End If",
      "         Dim baseItem As CoreSugarBaseItem = CType(pObj, CoreSugarBaseItem)",
      "         If baseItem <> NULL Then",
      "            Wrap = baseItem",
      "         Else",
      "            Wrap = New CoreSugarObjectWrapper(pObj)",
      "         End If",
      "      End Function",
      "",
      "      Protected Function Unwrap(pItem As CoreSugarBaseItem) As TObject",
      "         If pItem = NULL Then",
      "            Unwrap = NULL",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarObjectWrapper = CType(pItem, CoreSugarObjectWrapper)",
      "         If wrapper <> NULL Then",
      "            Unwrap = wrapper.value",
      "         Else",
      "            Unwrap = pItem",
      "         End If",
      "      End Function",
      "   End Class",
      "",
      "   Class CoreSugarListDateTime",
      "      Inherits CoreSugarList",
      "",
      "      Sub New()",
      "         MyBase.New(True)",
      "      End Sub",
      "",
      "      Overrides Function CreateInstance() As CoreSugarList",
      "         CreateInstance = New CoreSugarListDateTime()",
      "      End Function",
      "",
      "      Protected Function Wrap(pValue As TDateTime) As CoreSugarBaseItem",
      "         Wrap = New CoreSugarDateTimeWrapper(pValue)",
      "      End Function",
      "",
      "      Protected Function Unwrap(pItem As CoreSugarBaseItem) As TDateTime",
      "         If pItem = NULL Then",
      "            Unwrap = 0",
      "            Exit Function",
      "         End If",
      "         Dim wrapper As CoreSugarDateTimeWrapper = CType(pItem, CoreSugarDateTimeWrapper)",
      "         If wrapper <> NULL Then",
      "            Unwrap = wrapper.value",
      "         Else",
      "            Unwrap = 0",
      "         End If",
      "      End Function",
      "   End Class",
      "",
      "   Class TList<T>",
      "      Inherits CoreSugarListObjects",
      "",
      "      Sub New(pOwnsObjects As Boolean = True)",
      "         MyBase.New(pOwnsObjects)",
      "      End Sub",
      "",
      "      Overrides Function CreateInstance() As CoreSugarList",
      "         CreateInstance = New TList<T>(me.OwnsObjects)",
      "      End Function",
      "",
      "      Public Shared Function Of(p1 As T = NULL, p2 As T = NULL, p3 As T = NULL, p4 As T = NULL, p5 As T = NULL) As TList<T>",
      "         Dim list As New TList<T>()",
      "         If p1 <> NULL Then list.Push(p1)",
      "         If p2 <> NULL Then list.Push(p2)",
      "         If p3 <> NULL Then list.Push(p3)",
      "         If p4 <> NULL Then list.Push(p4)",
      "         If p5 <> NULL Then list.Push(p5)",
      "         Of = list",
      "      End Function",
      "",
      "      Function Push(pValue As T) As TList<T>",
      "         MyBase.Push(me.Wrap(pValue))",
      "         Push = me",
      "      End Function",
      "",
      "      Sub Add(pValues As TList<T>)",
      "         MyBase.Add(pValues)",
      "      End Sub",
      "",
      "      Function Pop() As T",
      "         Pop = CType(me.Unwrap(MyBase.Pop()), T)",
      "      End Function",
      "",
      "      Function Shift() As T",
      "         Shift = CType(me.Unwrap(MyBase.Shift()), T)",
      "      End Function",
      "",
      "      Function Unshift(pValue As T) As TList<T>",
      "         MyBase.Unshift(me.Wrap(pValue))",
      "         Unshift = me",
      "      End Function",
      "",
      "      Property Item(pIndex As Integer) As T",
      "         Get",
      "            Item = CType(me.Unwrap(me.GetItemInternal(pIndex)), T)",
      "         End Get",
      "         Set(pValue As T)",
      "            me.SetItemInternal(pIndex, me.Wrap(pValue))",
      "         End Set",
      "      End Property",
      "",
      "      Function Filter(pHandler As SugarFindDel, extra As Variant) As TList<T>",
      "         Filter = CType(MyBase.Filter(pHandler, extra), TList<T>)",
      "      End Function",
      "",
      "      Function Map(pHandler As SugarMapDel, extra As Variant) As CoreSugarList",
      "         Map = MyBase.Map(pHandler, extra)",
      "      End Function",
      "",
      "      Function ForEach(pHandler As SugarForEachDel, extra As Variant) As TList<T>",
      "         MyBase.ForEach(pHandler, extra)",
      "         ForEach = me",
      "      End Function",
      "",
      "      Function Slice(pStart As Integer, pCount As Integer) As TList<T>",
      "         Slice = CType(MyBase.Slice(pStart, pCount), TList<T>)",
      "      End Function",
      "",
      "      Function Reverse() As TList<T>",
      "         MyBase.Reverse()",
      "         Reverse = me",
      "      End Function",
      "",
      "      Function Sort(pHandler As SugarSortDel, pAsc As Boolean, extra As Variant) As TList<T>",
      "         MyBase.Sort(pHandler, pAsc, extra)",
      "         Sort = me",
      "      End Function",
      "   End Class",
      "",
      "End Namespace"
    ].join("\r\n");
  }
});
