import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Exception",
    kind: "class",
    type: "Exception",
    isShared: false,
    isPrivate: false,
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    inheritsFrom: "TObject",
    description: "Classe de exceção genérica para representar erros e situações excepcionais.",
  },

  // ───────── Construtor (overloads) ─────────
  {
    name: "Create",
    kind: "method",
    type: "Exception",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pMsg", type: "String", isByRef: false, isOptional: false }],
    overloads: [[]],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description:
      "Construtor. Aceita uma string de mensagem para inicializar a exceção ou nenhum argumento para criar uma exceção vazia.",
  },

  // ───────── Inserção / leitura ─────────
  {
    name: "BaseException",
    kind: "property",
    type: "Exception",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description:
      "Propriedade que retorna a exceção base (base exception) associada a esta exceção, ou nil se não houver uma exceção base. Permite acessar detalhes da exceção original em casos de encadeamento de exceções (exception chaining).",
  },
  {
    name: "HelpContext",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna o contexto de ajuda associado à exceção.",
  },
  {
    name: "InnerException",
    kind: "property",
    type: "Exception",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description:
      "Retorna a exceção interna associada a esta exceção, ou nil se não houver uma exceção interna.",
  },
  {
    name: "Message",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],

    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna a mensagem de erro associada à exceção.",
  },
  {
    name: "StackTrace",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna a pilha de rastreamento associada à exceção.",
  },

  // ───────── Persistência ─────────
  {
    name: "StackInfo",
    kind: "property",
    type: "Pointer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna informações sobre a pilha de chamadas associada à exceção.",
  },
  {
    name: "_GetMessage",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna a mensagem de erro associada à exceção.",
  },
  {
    name: "_SetMessage",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pValue", type: "String", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Define a mensagem de erro associada à exceção.",
  },
  {
    name: "_getHelpContext",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Retorna o contexto de ajuda associado à exceção.",
  },
  {
    name: "_setHelpContext",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pValue", type: "Integer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "Exception",
    description: "Define o contexto de ajuda associado à exceção.",
  },
];
