import type { SystemSymbolInfo } from "../types";
import { defineEnum } from "../symbol-helpers";

export const symbols: SystemSymbolInfo[] = defineEnum({
  name: "TColor",
  description:
    "Cor em formato Integer (BGR de 24 bits, opcionalmente com prefixo do system color). Acessível globalmente, sem Imports. Use uma constante clXxx ou a função RGB(r, g, b).",
  values: [
    ["clBlack", "Preto (0x000000)."],
    ["clMaroon", "Marrom-escuro (0x000080)."],
    ["clGreen", "Verde (0x008000)."],
    ["clOlive", "Verde-oliva (0x008080)."],
    ["clNavy", "Azul-marinho (0x800000)."],
    ["clPurple", "Roxo (0x800080)."],
    ["clTeal", "Verde-azulado (0x808000)."],
    ["clGray", "Cinza (0x808080)."],
    ["clSilver", "Prata (0xC0C0C0)."],
    ["clRed", "Vermelho (0x0000FF)."],
    ["clLime", "Verde-limão (0x00FF00)."],
    ["clYellow", "Amarelo (0x00FFFF)."],
    ["clBlue", "Azul (0xFF0000)."],
    ["clFuchsia", "Magenta/fúcsia (0xFF00FF)."],
    ["clAqua", "Ciano/aqua (0xFFFF00)."],
    ["clLtGray", "Cinza-claro — alias para clSilver."],
    ["clDkGray", "Cinza-escuro — alias para clGray."],
    ["clWhite", "Branco (0xFFFFFF)."],
    ["clMoneyGreen", "Verde-pastel (cor de cédula)."],
    ["clSkyBlue", "Azul-céu."],
    ["clCream", "Creme (off-white)."],
    ["clMedGray", "Cinza-médio."],
    ["clBtnFace", "Cor da face de botão padrão do sistema."],
    ["clBtnShadow", "Cor de sombra de botão padrão do sistema."],
    ["clBtnHighlight", "Cor de destaque (highlight) de botão padrão do sistema."],
    ["clBtnText", "Cor do texto do botão padrão do sistema."],
    ["clActiveCaption", "Cor da barra de título da janela activa."],
    ["clInactiveCaption", "Cor da barra de título de janela inativa."],
    ["clCaptionText", "Cor do texto da barra de título ativa."],
    ["clMenu", "Cor de fundo de menus do sistema."],
    ["clMenuText", "Cor do texto de menus."],
    ["clHighlight", "Cor de fundo de itens selecionados."],
    ["clHighlightText", "Cor de texto de itens selecionados."],
    ["clScrollBar", "Cor de fundo de barras de rolagem."],
    ["clWindow", "Cor de fundo padrão de janelas."],
    ["clWindowText", "Cor de texto padrão de janelas."],
    ["clWindowFrame", "Cor de borda de janela."],
    ["clBackground", "Cor de fundo da área de trabalho."],
    ["clAppWorkSpace", "Cor da área de trabalho MDI."],
    ["clInfoBk", "Cor de fundo de tooltips."],
    ["clInfoText", "Cor do texto de tooltips."],
    ["cl3DLight", "Cor 3D clara (highlight de bordas)."],
    ["cl3DDkShadow", "Cor 3D escura (sombra profunda)."],
    ["clGrayText", "Cor de texto desabilitado."],
    ["clNone", "Sem cor (transparente em alguns contextos)."],
    ["clDefault", "Cor padrão (deixa o componente decidir)."],
  ],
});
