import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TFont",
    kind: "class",
    type: "TFont",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    description:
      "Fonte usada por controles e elementos visuais. Expõe nome, tamanho, estilo e cor.",
  },
  {
    name: "Name",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Nome da fonte.",
  },
  {
    name: "Size",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Tamanho da fonte em pontos.",
  },
  {
    name: "Height",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Altura da fonte em pixels lógicos.",
  },
  {
    name: "Color",
    kind: "property",
    type: "TColor",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Cor do texto renderizado com a fonte.",
  },
  {
    name: "Style",
    kind: "property",
    type: "TFontStyle",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Estilo da fonte (bold, italic, underline, strikeout).",
  },
  {
    name: "Bold",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está em negrito.",
  },
  {
    name: "Italic",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está em itálico.",
  },
  {
    name: "Underline",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está sublinhada.",
  },
  {
    name: "StrikeOut",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está riscada.",
  },
  {
    name: "Orientation",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Orientação da fonte em graus.",
  },
  {
    name: "Charset",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Charset da fonte.",
  },
  {
    name: "Pitch",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Pitch da fonte.",
  },
  {
    name: "Quality",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Quality da fonte.",
  },
  {
    name: "GetBold",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Retorna se a fonte está em negrito.",
  },
  {
    name: "GetItalic",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Retorna se a fonte está em itálico.",
  },
  {
    name: "GetUnderline",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Retorna se a fonte está sublinhada.",
  },
  {
    name: "GetStrikeOut",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Retorna se a fonte está riscada.",
  },
  {
    name: "SetBold",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pValue",
        type: "Boolean",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está em negrito.",
  },
  {
    name: "SetItalic",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pValue",
        type: "Boolean",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está em itálico.",
  },
  {
    name: "SetUnderline",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pValue",
        type: "Boolean",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está sublinhada.",
  },
  {
    name: "SetStrikeOut",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pValue",
        type: "Boolean",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: range,
    fileUri: "system://library",
    containerName: "TFont",
    description: "Define se a fonte está riscada.",
  },
];
