import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Accept",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Define no cabeçalho HTTP qual o tipo de resposta esperado.",
  },
  {
    name: "Body",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Utilizado para enviar dados ao servidor.",
  },
  {
    name: "ContentType",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Diz para o servidor qual o tipo de conteúdo sendo enviado.",
  },
  {
    name: "Password",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Define a senha do usuário para autenticação.",
  },
  {
    name: "ResponseCode",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Obtém o código da resposta HTTP do servidor.",
  },
  {
    name: "ResponseText",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Obtém o texto da resposta HTTP do servidor.",
  },
  {
    name: "SslVersion",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Define a versão do SSL ou TLS utilizada para a conexão.",
  },
  {
    name: "Get",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pURL",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Solicita a representação de um recurso específico.",
  },
  {
    name: "Post",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pURL",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Envia dados para um URI específico.",
  },
  {
    name: "Put",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pURL",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Coloca um arquivo ou recurso em um URI específico.",
  },
  {
    name: "AddCustomHeader",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pHeader",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "THTTP",
    description: "Adiciona um header customizado à requisição HTTP.",
  },
  {
    name: "THTTP",
    kind: "class",
    type: "THTTP",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    inheritsFrom: "TObject",
    description: "Classe para realizar requisições HTTP (GET, POST, PUT).",
  },
];
