import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TMsg",
    kind: "structure",
    type: "TMsg",
    isShared: true,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    description:
      "Estrutura de mensagem do Windows. Contém informações sobre eventos de sistema e interface, como movimento do mouse, teclado, redimensionamento de janelas e mensagens de pintação (WM_PAINT). Usada internamente pelo VCL e acessível em procedimentos de janela (WindowProc).",
  },
  {
    name: "hWnd",
    kind: "property",
    type: "Cardinal",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Handle da janela que recebeu a mensagem.",
  },
  {
    name: "message",
    kind: "property",
    type: "Cardinal",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Código da mensagem (ex: WM_PAINT, WM_KEYDOWN).",
  },
  {
    name: "wParam",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Parâmetro 1 da mensagem (geralmente informações do mouse/teclado).",
  },
  {
    name: "lParam",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Parâmetro 2 da mensagem (geralmente coordenadas ou estado do controle).",
  },
  {
    name: "time",
    kind: "property",
    type: "Cardinal",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Timestamp da mensagem.",
  },
  {
    name: "pt",
    kind: "property",
    type: "TPoint",
    isShared: false,
    isPrivate: false,
    range: SYSTEM_RANGE,
    fileUri: SYSTEM_URI,
    containerName: "TMsg",
    description: "Coordenadas do mouse/cursor no momento da mensagem.",
  },
];
