import { SYSTEM_RANGE, SYSTEM_URI } from "../symbol-helpers";
import type { SystemSymbolInfo } from "../types";

const range = { startLine: 0, startChar: 0, endLine: 0, endChar: 0 } as const;

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TRect",
    kind: "structure",
    type: "TRect",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    description:
      "Retângulo definido por duas coordenadas (Left, Top) e (Right, Bottom). Estrutura padrão da VCL, acessível globalmente. Usado em BoundsRect, ClientRect, áreas de desenho do Canvas e funções de geometria.",
  },

  {
    name: "Left",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Coordenada X do canto superior esquerdo.",
  },
  {
    name: "Top",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Coordenada Y do canto superior esquerdo.",
  },
  {
    name: "Right",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Coordenada X do canto inferior direito (não inclusiva).",
  },
  {
    name: "Bottom",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Coordenada Y do canto inferior direito (não inclusiva).",
  },
  {
    name: "Width",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Largura calculada (Right - Left).",
  },
  {
    name: "Height",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Altura calculada (Bottom - Top).",
  },
  {
    name: "TopLeft",
    kind: "property",
    type: "TPoint",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Canto superior esquerdo como TPoint.",
  },
  {
    name: "BottomRight",
    kind: "property",
    type: "TPoint",
    isShared: false,
    isPrivate: false,
    range: range,
    fileUri: SYSTEM_URI,
    containerName: "TRect",
    description: "Canto inferior direito como TPoint.",
  },
];
