import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Date",
    kind: "class",
    type: "Date",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    description: "Tipo Delphi/Data7 representando data e hora.",
  },
  {
    name: "ToString",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Converte o valor de data e hora para string formatada.",
  },
  {
    name: "Year",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o ano correspondente da data.",
  },
  {
    name: "Month",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o mês correspondente da data.",
  },
  {
    name: "Day",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o dia do mês correspondente da data.",
  },
  {
    name: "Hour",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna a hora correspondente.",
  },
  {
    name: "Minute",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o minuto correspondente.",
  },
  {
    name: "Second",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o segundo correspondente.",
  },
  {
    name: "Date",
    kind: "class",
    type: "Date",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    inheritsFrom: "TObject",
    description: "Representa uma data no ecossistema Delphi/Data7.",
  },
  {
    name: "Year",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o ano correspondente.",
  },
  {
    name: "Month",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o mês correspondente.",
  },
  {
    name: "Day",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Retorna o dia do mês.",
  },
  {
    name: "ToString",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pFormat",
        type: "String",
        isByRef: false,
        isOptional: true,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: 'Converte a data para String utilizando um formato opcional (ex: "dd/mm/yyyy").',
  },
  {
    name: "AddDays",
    kind: "method",
    type: "Date",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pDays",
        type: "Double",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Adiciona ou subtrai dias da data especificada.",
  },
  {
    name: "AddMonths",
    kind: "method",
    type: "Date",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pMonths",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Adiciona ou subtrai meses da data especificada.",
  },
  {
    name: "AddYears",
    kind: "method",
    type: "Date",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pYears",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Date",
    description: "Adiciona ou subtrai anos da data especificada.",
  },
];
