import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "Double",
    kind: "class",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    inheritsFrom: "TPrimitive",
    fileUri: "system://library",
    description: "Tipo primitivo de número de ponto flutuante de precisão dupla de 64 bits.",
  },
  // {
  //   name: "ToString",
  //   kind: "method",
  //   type: "String",
  //   isShared: false,
  //   isPrivate: false,
  //   parameters: [],
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: "system://library",
  //   containerName: "Double",
  //   description: "Converte o valor de ponto flutuante para uma string.",
  // },
  // {
  //   name: "Double",
  //   kind: "class",
  //   type: "Double",
  //   isShared: false,
  //   isPrivate: false,
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: "system://library",
  //   inheritsFrom: "TObject",
  //   description: "Representa um número de ponto flutuante de precisão dupla (tipo primitivo).",
  // },
  // {
  //   name: "ToString",
  //   kind: "method",
  //   type: "String",
  //   isShared: false,
  //   isPrivate: false,
  //   parameters: [
  //     {
  //       name: "pFormat",
  //       type: "String",
  //       isByRef: false,
  //       isOptional: true,
  //     },
  //   ],
  //   range: {
  //     startLine: 0,
  //     startChar: 0,
  //     endLine: 0,
  //     endChar: 0,
  //   },
  //   fileUri: "system://library",
  //   containerName: "Double",
  //   description:
  //     "Converte o valor Double para sua representação em String usando um formato opcional.",
  // },
  {
    name: "Round",
    kind: "method",
    type: "Double",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pDecimals",
        type: "Integer",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "Double",
    description: "Arredonda o valor para o número de casas decimais especificado.",
  },
];
