import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TObject",
    kind: "class",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    inheritsFrom: "System.Classes.TObject",
    description: "Classe base para todos os objetos no ambiente Data7/Delphi.",
  },
  {
    name: "ToString",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna a representação textual do objeto.",
  },
  {
    name: "Free",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Libera a memória alocada pelo objeto (Destrutor nativo Delphi).",
  },
  {
    name: "GetHashCode",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna o código hash do objeto (identificador único no ecossistema Delphi).",
  },
  {
    name: "ClassName",
    kind: "method",
    type: "String",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna o nome da classe do objeto como uma string.",
  },
  {
    name: "ClassNameIs",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pName",
        type: "String",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Verifica se o nome da classe do objeto é igual ao nome fornecido.",
  },
  {
    name: "ClassParent",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna a classe pai direto da classe deste objeto.",
  },
  {
    name: "InheritsFrom",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pClass",
        type: "TObject",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Verifica se a classe do objeto herda de uma determinada classe.",
  },
  {
    name: "DisposeOf",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Libera a memória e destrói o objeto se ele tiver sido criado dinamicamente.",
  },

  // ───────── RTTI e instância (membros expostos pelo autocomplete original) ─────────
  {
    name: "ClassType",
    kind: "method",
    type: "TClass",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Retorna a referência ao tipo (metaclasse TClass) do objeto, útil em comparações TObject1.ClassType = TObject2.ClassType.",
  },
  {
    name: "InstanceSize",
    kind: "method",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Retorna o tamanho em bytes alocado para uma instância da classe (sizeof do objeto em memória).",
  },
  {
    name: "AfterConstruction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Hook chamado logo após o último construtor da hierarquia; permite executar lógica que depende do objeto totalmente construído.",
  },
  {
    name: "Dispatch",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Message", type: "PVOID", isByRef: true, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Despacha uma mensagem (Windows ou definida pelo usuário) para o handler correspondente; chama DefaultHandler quando nenhum método casa.",
  },
  {
    name: "DefaultHandler",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Message", type: "PVOID", isByRef: true, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Handler invocado por Dispatch quando nenhum método específico processa a mensagem.",
  },
  {
    name: "NewInstance",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Aloca memória para uma nova instância (uso baixo nível — chamado pelo runtime no Create).",
  },
  {
    name: "FreeInstance",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Libera a memória de uma instância (uso baixo nível — chamado pelo runtime no Destroy).",
  },
  {
    name: "Equals",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Obj", type: "TObject", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Compara este objeto a outro (igualdade lógica) — a implementação padrão usa identidade de referência.",
  },
  {
    name: "FieldAddress",
    kind: "method",
    type: "Pointer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Name", type: "ShortString", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Retorna o endereço de um campo da classe a partir do nome publicado (RTTI legacy).",
  },
  {
    name: "MethodAddress",
    kind: "method",
    type: "Pointer",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Name", type: "ShortString", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna o endereço de um método publicado a partir do nome (RTTI legacy).",
  },
  {
    name: "MethodName",
    kind: "method",
    type: "ShortString",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "Address", type: "Pointer", isByRef: false, isOptional: false }],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Retorna o nome de um método publicado a partir de seu endereço (RTTI legacy).",
  },

  // ───────── Constructor / Destructor padrões ─────────
  {
    name: "Create",
    kind: "method",
    type: "TObject",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description: "Construtor padrão sem parâmetros (descendentes geralmente sobrescrevem).",
  },
  {
    name: "Destroy",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Destrutor virtual da classe — prefira `Free` para liberar a instância (Free testa Self antes de chamar Destroy).",
  },
  {
    name: "BeforeDestruction",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Hook chamado imediatamente antes de o primeiro destrutor da hierarquia executar; permite limpeza que depende de o objeto ainda estar íntegro.",
  },
  {
    name: "SafeCallException",
    kind: "method",
    type: "HRESULT",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "ExceptObject", type: "TObject", isByRef: false, isOptional: false },
      { name: "ExceptAddr", type: "Pointer", isByRef: false, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Tratador padrão de exceções para métodos `safecall` — converte a exceção em HRESULT para callers COM.",
  },
  {
    name: "GetInterface",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      { name: "IID", type: "TGUID", isByRef: false, isOptional: false },
      { name: "Obj", type: "PVOID", isByRef: true, isOptional: false },
    ],
    range: { startLine: 0, startChar: 0, endLine: 0, endChar: 0 },
    fileUri: "system://library",
    containerName: "TObject",
    description:
      "Tenta obter a interface identificada por IID a partir deste objeto; preenche `Obj` quando a interface é suportada e retorna True/False.",
  },
];
