import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  // WhatsappSend class
  {
    name: "WhatsappSend",
    kind: "class",
    type: "WhatsappSend",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    inheritsFrom: "TObject",
    description: "Classe nativa do sistema para envio de mensagens via WhatsApp.",
  },
  {
    name: "SendMessage",
    kind: "method",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    parameters: [
      {
        name: "pMessage",
        type: "WhatsappMessage",
        isByRef: false,
        isOptional: false,
      },
    ],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappSend",
    description: "Envia uma mensagem do WhatsApp e retorna True em caso de sucesso.",
  },

  // WhatsappMessage class
  {
    name: "WhatsappMessage",
    kind: "class",
    type: "WhatsappMessage",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    inheritsFrom: "TObject",
    description: "Representa uma mensagem do WhatsApp a ser enviada.",
  },
  {
    name: "Recipient",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappMessage",
    description: "Número do destinatário no formato internacional (ex: 5511999999999).",
  },
  {
    name: "Subject",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappMessage",
    description: "Assunto da mensagem do WhatsApp.",
  },
  {
    name: "Content",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappMessage",
    description: "Texto/Conteúdo da mensagem do WhatsApp.",
  },
  {
    name: "Signature",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappMessage",
    description: "Assinatura da mensagem do WhatsApp.",
  },
  {
    name: "Attachments",
    kind: "property",
    type: "TStringList",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "WhatsappMessage",
    description: "Lista de caminhos de arquivos anexos.",
  },
];
