import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TFDParam",
    kind: "class",
    type: "TFDParam",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "SQL",
    inheritsFrom: "TObject",
    description: "Representa um parâmetro em uma consulta SQL.",
  },
  {
    name: "AsInteger",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como Integer.",
  },
  {
    name: "AsString",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como String.",
  },
  {
    name: "AsFloat",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como Double/Float.",
  },
  {
    name: "AsBoolean",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como Boolean.",
  },
  {
    name: "Value",
    kind: "property",
    type: "Variant",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como Variant.",
  },
  {
    name: "AsDateTime",
    kind: "property",
    type: "TDateTime",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TFDParam",
    description: "Obtém ou define o valor do parâmetro como TDateTime.",
  },
];
