import type { SystemSymbolInfo } from "../types";

export const symbols: SystemSymbolInfo[] = [
  {
    name: "TField",
    kind: "class",
    type: "TField",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "SQL",
    description: "Representa um campo retornado de uma consulta de banco de dados.",
  },
  {
    name: "AsString",
    kind: "property",
    type: "String",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em String.",
  },
  {
    name: "AsInteger",
    kind: "property",
    type: "Integer",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em Integer.",
  },
  {
    name: "AsFloat",
    kind: "property",
    type: "Double",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em Double/Float.",
  },
  {
    name: "AsBoolean",
    kind: "property",
    type: "Boolean",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em Boolean.",
  },
  {
    name: "AsDate",
    kind: "property",
    type: "TDateTime",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em TDateTime (somente data).",
  },
  {
    name: "AsDateTime",
    kind: "property",
    type: "TDateTime",
    isShared: false,
    isPrivate: false,
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Valor do campo convertido em TDateTime (data e hora).",
  },
  {
    name: "SaveToFile",
    kind: "method",
    type: "Void",
    isShared: false,
    isPrivate: false,
    parameters: [{ name: "pFileName", type: "String", isByRef: false, isOptional: false }],
    range: {
      startLine: 0,
      startChar: 0,
      endLine: 0,
      endChar: 0,
    },
    fileUri: "system://library",
    containerName: "TField",
    description: "Salva o conteúdo do campo em um arquivo.",
  },
];
